### ISSUE TITLE
"Repeater" in the page title

### ISSUE THREAD

**Issue by g0wfv** [dg9vh/MMDVMHost-Dashboard#10]
MMDVM-Dashboard by DG9VH for **Repeater**: G0WFV

An enhancement for you as you now reference the ini file, look at the Duplex flag and substitute the word _Repeater_ for _Gateway_ in the title if it's Duplex=0

**Comment by dg9vh** [comment]
Also corr in https://github.com/dg9vh/MMDVMHost-Dashboard/commit/26b8b15d2b2ed29b56f17d7de94019a4564f10c6

Mni tnx for your ideas - keep going on! You help to improve!
