### ISSUE TITLE
YSF linked to  --> don't work

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#102]
Hi dear

sorry for the new ticket :)

the YSF linked to  , seems doesn't work, the repeater run the YSFGateway correctly If I connect some YSFreflector in the dashboard I don't see the connection .

![image](https://cloud.githubusercontent.com/assets/16877668/23580912/190683f4-010b-11e7-8979-ed83d72517c9.png)

Thank you

73

**Comment by dg9vh** [comment]
Could be a wrong path to YSF log. Please check.Am 04.03.2017 18:48 schrieb iw9grl <notifications@github.com>:Hi dear
sorry for the new ticket :)
the YSF linked to  , seems doesn't work, the repeater run the YSFGateway correctly If I connect some YSFreflector in the dashboard I don't see the connection .

Thank you
73

**Comment by iw9grl** [comment]
Thank you again ...... I put a wrong path, now it works ............ thank you for the patience  :)


73
