### ISSUE TITLE
a simple multi-language version

### ISSUE THREAD

**Issue by s-s-s** [dg9vh/MMDVMHost-Dashboard#109]
Hi!
I want to propose to make a simple multi-language version.
Here https://github.com/s-s-s/MMDVMHost-Dashboard_sss I started.
Maybe it will be interesting to add  to project
73! 
R2AJV
dashboard - http://250203.radiocilt.ru:8082/

**Comment by dg9vh** [comment]
Good idea... maybe we should start doing it "the right way" with using gettext-translation-mechanism with po/mo-files? I would prepare the sources to be translateable...

**Comment by pjao** [comment]
I'll help with Portuguese!

**Comment by s-s-s** [comment]
I'm not a programmer, just a coder. I can take up the Russian language on any chosen path of development

**Comment by dg9vh** [comment]
@s-s-s You are welcome to do it :-) I would try to get all prepared this evening when Family is in place and all the evening rituals are done :-)

**Comment by dg9vh** [comment]
Internationalization is in progress... I made many of the texts translateable... this evening functions.php would follow with a few more outputs that are sill not translateable.

I would generate an actual messages.pot within the root-directory of the dashboard that contains all fields and texts to translate into the several languages. I made an example-translation for german by my own that you can find in locale/de_DE now...

Also a little documentation on how to procede is in the root-dir...

**Comment by pjao** [comment]
When we have "Locale" empty on setup.php it makes an error. Must have defined by default "en_GB" and not "".

2017-03-15 12:41:12: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  include(locale//settings.php): failed to open stream: No such file or directory in /var/www/html/MMDVMHost-Dashboard/ajax.php on line 7
2017-03-15 12:41:12: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  include(): Failed opening 'locale//settings.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/MMDVMHost-Dashboard/ajax.php on line 7
2017-03-15 12:41:12: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Use of undefined constant LANG_LOCALE - assumed 'LANG_LOCALE' in /var/www/html/MMDVMHost-Dashboard/ajax.php on line 9
2017-03-15 12:41:12: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Use of undefined constant LANG_LOCALE - assumed 'LANG_LOCALE' in /var/www/html/MMDVMHost-Dashboard/ajax.php on line 10
2017-03-15 12:41:12: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Use of undefined constant LANG_LOCALE - assumed 'LANG_LOCALE' in /var/www/html/MMDVMHost-Dashboard/ajax.php on line 13

**Comment by pjao** [comment]
Another thing that I've noticed, the "CPU-Usage" doesn't get painted green if not using "en_GB".


![sem titulo](https://cloud.githubusercontent.com/assets/6640329/23949074/a76ad6b6-097d-11e7-9d00-7703b448d76f.png)

![sem titulo2](https://cloud.githubusercontent.com/assets/6640329/23949079/ad11f0ea-097d-11e7-8923-a57c0c03a34c.png)

**Comment by dg9vh** [comment]
tnx for info... would check it this evening and make changes to set a default if not set...

**Comment by dg9vh** [comment]
made it now... worked on my side...

**Comment by dg9vh** [comment]
@s-s-s Sergei, you can start translating, I think we found all parts to be translated. If starting, just take the messages.pot in the root-directory and fill the ""-parts after "msgstr" with your translation. Then you could take the folder de_DE within locale as example and create a subdirectory containing the same structure, modify the settings.php with the correct locale-information and put the messages.pot as messages.po into it... that would be all to be done. If you would, you could create the .mo file with msgfmt messages.po -o messages.mo - if not, I would do it...

**Comment by s-s-s** [comment]
@dg9vh , I already did and check it right now before publishing  :)

**Comment by dg9vh** [comment]
@s-s-s You are my hero of the day... I also had an offer of a guy from sweeden to do the sweedish and danish part... I know how much work and time it is - I did the german one by myself and needed good one hour for doing it :-) So my offer for all translators is: If we meet sometimes somewhere, your beer is sure :-)

**Comment by pjao** [comment]
@dg9vh ah ah ah You should try Portuguese beer also ;)

Can't understand the problem (http://ct2jay.ham-radio-op.net:7777/)

**Comment by dg9vh** [comment]
@pjao what problem do you mean? your link looks nice - but I can't understand one word :-)

But you also get a beer if we meet once... sure

**Comment by dg9vh** [comment]
... I should start a crowd-funding campagne to finance all the beer we need if this would be translated in all languages around the world :-)

**Comment by s-s-s** [comment]
Added Russian language
https://github.com/dg9vh/MMDVMHost-Dashboard/pull/120

offtop:
I love Czech beer, but we have no Czech translation :)

**Comment by pjao** [comment]
No green bar, only grey (CPU-Nutzung).

![sem titulo3](https://cloud.githubusercontent.com/assets/6640329/23953722/5ce3458c-098d-11e7-962d-803ffc44b234.png)

**Comment by dg9vh** [comment]
this is fixed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/273657ee83f8da14d8f37243628b380642c11c5f

**Comment by pjao** [comment]
@dg9vh good work! One beer for you!

**Comment by dg9vh** [comment]
gracias :-)

**Comment by dg9vh** [comment]
Since this project is running and we produce a lot of beer, I'll close this now :-)
