### ISSUE TITLE
MMDVM.ini FQFN

### ISSUE THREAD

**Issue by g0wfv** [dg9vh/MMDVMHost-Dashboard#11]
You have hardcoded the filename MMDVM.ini.

The inifile can be called anything.

Explicitly asking for the FQFN to the inifile rather than just the FQPN and harcoding the FN may be more appropriate?

**Comment by dg9vh** [comment]
In https://github.com/dg9vh/MMDVMHost-Dashboard/commit/26b8b15d2b2ed29b56f17d7de94019a4564f10c6 corrected, too...

ALso here mni tnx!
