### ISSUE TITLE
"not cfmd" ?

### ISSUE THREAD

**Issue by marrold** [dg9vh/MMDVMHost-Dashboard#122]
Hi,

Please could someone explain what "not cfmd" means? I've checked the source code and searched for generic DMR terms that refer to cfmd, but I cannot find the answer.

Thanks again for the great software.

**Comment by ea4fvb** [comment]
lol... neither me ;)

**Comment by dg9vh** [comment]
It's simply a short handle for not confirmed...

It's sometimes shown behind the reflectors number for DMR, if no confirmation of the master was given after a change of reflector linking.

So far, so clear?
