### ISSUE TITLE
"View Log" - Should change the menu from main index

### ISSUE THREAD

**Issue by pjao** [dg9vh/MMDVMHost-Dashboard#128]
Just notice one thing...

If you chose, "View Log" the menu is just like the main menu from index. Than if you select any of the options it asks for an bad url.

That should not be as other, with only the "Home" button?

I could make the change, but I need to ear from you @dg9vh, do you have another idea?

**Comment by dg9vh** [comment]
PSE do it

**Comment by pjao** [comment]
Done with https://github.com/dg9vh/MMDVMHost-Dashboard/pull/129
