### ISSUE TITLE
Starting and stopping single mode of dmr or dstar/more buttons for switching networks

### ISSUE THREAD

**Issue by s-s-s** [dg9vh/MMDVMHost-Dashboard#130]
Hi all!
I think that it would be not bad if there were a another couple options in the dashboard - Starting and stopping single mode of dmr and dstar.
To do this, you can have a different files with settings. For example, such
MMDVM.ini to muti-mode work
MMDVM_dmr.ini for DMR
MMDVM_dstar.ini for DSTAR
Can someone write the correct php-command for a single-mode launch.
Maybe start the MMDVMHost in single-mode can do like so :
exec( "sudo '/usr/bin/screen -S MMDVMHost -D -m /home/pi/MMDVMHost/MMDVMHost /home/pi/MMDVM_dmr.ini'" ); 

and stop like :
exec( "/usr/bin/screen -S MMDVMHost -X quit" );

73!
R2AJV

**Comment by dg9vh** [comment]
Hi, I would take a look what comfortable way we find here...

**Comment by dg9vh** [comment]
@s-s-s @dc7jzb I made a first attempt to make your wishes possible... hope, the users would get how to configure the thing using the /config/networks.php ... maybe I should build up a configuration-manager for this, too :-)

**Comment by pjao** [comment]
@dg9vh Excellent job! 

Përmirësime të shpejta!

**Comment by dc7jzb** [comment]
Hello Kim,
it looks good.

But I have one Problem, I have modified the network.php.
I have redefined the DStar Singlemode Button to connect your Master in
DMRplus.

In my understandings I have to change the "ini":"DSTAR" to the Name of the
"new" .ini file.
Here I want to start with the DLSAAR.ini, so I have changed it to
"ini":"DLSAAR".
The DLSAAR.ini is correct in the MMDVMHOST Directory, and it works with my
shellscript.
But the Switch over only works with it when I will give it a "DSTAR.ini"
and change the network.php back to the original DSTAR values.

Is there something what I'am doing wrong ?

With a fourth button I have the same Problem, it looks like the script
doesn't copy the .ini, or find it.
The host restarts with the last correct used Master.

73 de Mario, DC7JZB

>

**Comment by dg9vh** [comment]
@dc7jzb You have to copy the new ini into the directory from where the MMDVM.ini is loaded (as it is configured in setup.php). 
Are you sure, that the changes are really persistent in the network.php? Means: That you had write-permissions on the file with the editor?

In my production-environment I have a YSF.ini that runs as singlemode YSF and it works fine... so the Dashboard and the switching-mechanism works fine.

**Comment by s-s-s** [comment]
Also didn`t switch (

networks.php
```
<?php
$networks_json = '{
          "DMRPLUS":{
            "label":"Singlemode DMR",
                "ini":"DMRPLUS",
                "logo":""
          },
          "BRANDMEISTER":{
            "label":"Multimode BrandMeister",
                "ini":"BRANDMEISTER",
                "logo":""
          },
          "DSTAR":{
            "label":"Singlemode D-STAR",
            "ini":"DSTAR",
            "logo":""
          }
}';

$networks = json_decode($networks_json, true);
?>

```

ls -l

> -rw-r--r-- 1 www-data www-data 2374 Mar 22 14:22 BRANDMEISTER.ini
> -rw-r--r-- 1 www-data www-data  2374 Mar 21 09:32 DMRPLUS.ini
> -rw-r--r-- 1 www-data www-data    12 Mar 24 20:13 MMDVM.ini
> -rw-r--r-- 1 www-data www-data  2374 Mar 21 09:33 DSTAR.ini
> -rw-r--r-- 1 www-data www-data  2374 Mar 21 09:32 DMR.ini

lighttpd.log

> 2017-03-24 20:12:24: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855
> 2017-03-24 20:12:24: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855
> 2017-03-24 20:12:48: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  exec(): Cannot execute a blank command in /var/www/html/html.new/scripts/switchnetwork.php on line 69
> 2017-03-24 20:12:59: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855
> 2017-03-24 20:12:59: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855
> 2017-03-24 20:13:09: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Warning:  exec(): Cannot execute a blank command in /var/www/html/html.new/scripts/switchnetwork.php on line 74
> 2017-03-24 20:13:19: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855
> 2017-03-24 20:13:19: (mod_fastcgi.c.2702) FastCGI-stderr: PHP Notice:  Undefined offset: 0 in /var/www/html/html.new/include/functions.php on line 855

**Comment by dg9vh** [comment]
@s-s-s the error-log is from the github-function in the footer... I think this is not the cause for not switching...
please post your config.php with masked passwords if any set to see, how you are switching between the files and restarting the service...

**Comment by dc7jzb** [comment]
Hi Kim,

I've checked it and all permissions are ok.
All the .ini's are under /opt/MMDVMHost, where the MMDVMHost is.
At the moment 4 Buttons are working with this setup.php :

<?php
$networks_json = '{
          "BRANDMEISTER":{
            "label":"BrandMeister",
                "ini":"BRANDMEISTER",
                "logo":"http://dc7jzb.de/files/logo/brandmeister-logo.png"
          },
          "DMRPLUS":{
            "label":"DMRplus DL-Berlin",
                "ini":"DMRPLUS",
                "logo":"http://dc7jzb.de/files/logo/dmrplus.jpg"
          },
          "DSTAR":{
            "label":"DMRPlus DL-Saar",
                "ini":"DSTAR",
                "logo":"http://dc7jzb.de/files/logo/dmrplus.jpg"
          },
          "C4FM":{
            "label":"DMRPlus LX",
            "ini":"C4FM",
            "logo":"http://dc7jzb.de/files/logo/dmrplus.jpg"

  }
}';


But it only works in this Version.
If I change the ini Name, or the first line of the part, like "C4FM" as
example to "DMRPLUS1", it doesn't work.

Damn , I see something ...
Could it be, that the first line for the Button ,has to have the same Name,
like the ini part ?


Have to try it..

73 de Mario, DC7JZB
Kim - DG9VH <notifications@github.com> schrieb am Fr., 24. März 2017 um
19:52:

**Comment by dc7jzb** [comment]
Ok , found my failure.
Now it works with five Buttons.

"DMRDL":{                        **_<--- Has to be the same Name like the. ini Name_**
             "label":"DMRPlus DL",
                 "ini":"DMRDL",            **_<--- ini Name has to be the same like the "Name" in the first Line_**
                 "logo":"http://dc7jzb.de/files/logo/dmrplus.jpg"
         }


Thanks for the fast implementation. 8)

73 de Mario, DC7JZB

**Comment by dg9vh** [comment]
Where was the fault?Am 24.03.2017 22:55 schrieb "Mario , DC7JZB" <notifications@github.com>:Ok , found my failure.
Now it works with five Buttons.

**Comment by dc7jzb** [comment]
If you take a "Name" for the Button (the Name in the first line), which is
different to the ini Name in the third line it does not find the right ini
File.
Both has to be the same Name.

As example :

"ThisIsAButtonName":{
            "label":"ThatsWhatISeeInDashboard",
            "ini":"NameOfIni",
            "logo":""

This will not work, because The first line "ThisIsAButtonName" is different
to the Name of the ini "NameOfIni"

When both is the same, it works at my Dashboard.

"NameOfIni":{
            "label":"ThatsWhatISeeInDashboard",
            "ini":"NameOfIni",
            "logo":""

Then it works. So it looks a little bit like it is searching for the ini
Name in the First Line, not at the ini field.
I don't know that you wanted it in this way, or it is a little bug. ;)

73 de Mario, DC7JZB

Kim - DG9VH <notifications@github.com> schrieb am Sa., 25. März 2017 um
08:38:

**Comment by dg9vh** [comment]
I think it is a bug. I'll take a look at it this evening.Am 25.03.2017 10:20 schrieb "Mario , DC7JZB" <notifications@github.com>:If you take a "Name" for the Button (the Name in the first line), which is
different to the ini Name in the third line it does not find the right ini
File.
Both has to be the same Name.

As example :

"ThisIsAButtonName":{
            "label":"ThatsWhatISeeInDashboard",
            "ini":"NameOfIni",
            "logo":""

This will not work, because The first line "ThisIsAButtonName" is different
to the Name of the ini "NameOfIni"

When both is the same, it works at my Dashboard.

"NameOfIni":{
            "label":"ThatsWhatISeeInDashboard",
            "ini":"NameOfIni",
            "logo":""

Then it works. So it looks a little bit like it is searching for the ini
Name in the First Line, not at the ini field.
I don't know that you wanted it in this way, or it is a little bug. ;)

73 de Mario, DC7JZB

Kim - DG9VH <notifications@github.com> schrieb am Sa., 25. März 2017 um
08:38:

**Comment by s-s-s** [comment]
@dg9vh it's my config.php

```
<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("MMDVMLOGPATH", "/var/log/MMDVMHost");
define("MMDVMINIPATH", "/home/pi");
define("MMDVMINIFILENAME", "MMDVM.ini");
define("MMDVMHOSTPATH", "/home/pi/mmdvm/MMDVMHost");
define("ENABLEXTDLOOKUP", "on");
define("TALKERALIAS", "on");
define("DMRIDDATPATH", "/home/pi/mmdvm/MMDVMHost/DMRIds.dat");
define("YSFGATEWAYLOGPATH", "");
define("YSFGATEWAYLOGPREFIX", "");
define("YSFGATEWAYINIPATH", "");
define("YSFGATEWAYINIFILENAME", "");
define("YSFHOSTSPATH", "");
define("YSFHOSTSFILENAME", "");
define("LINKLOGPATH", "/var/log/opendv");
define("IRCDDBGATEWAY", "ircddbgateway");
define("TIMEZONE", "Europe/Moscow");
define("LOCALE", "ru_RU");
define("LOGO", "logo3.jpg");
define("DMRPLUSLOGO", "");
define("BRANDMEISTERLOGO", "");
define("REFRESHAFTER", "60");
define("SHOWCPU", "on");
define("SHOWDISK", "on");
define("SHOWRPTINFO", "on");
define("SHOWMODES", "on");
define("SHOWLH", "on");
define("SHOWLOCALTX", "on");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "70");
define("ENABLENETWORKSWITCHING", "on");
define("SWITCHNETWORKUSER", "pi");
define("SWITCHNETWORKPW", "******");
define("ENABLEMANAGEMENT", "on");
define("VIEWLOGUSER", "pi");
define("VIEWLOGPW", "******");
define("HALTUSER", "pi");
define("HALTPW", "******");
define("REBOOTUSER", "pi");
define("REBOOTPW", "******");
define("RESTARTUSER", "pi");
define("RESTARTPW", "******");
define("REBOOTMMDVM", "sudo systemctl restart mmdvmhost.service");
define("REBOOTSYS", "sudo reboot");
define("HALTSYS", "sudo halt");
define("SHOWPOWERSTATE", "on");
define("POWERONLINEPIN", "");
define("POWERONLINESTATE", "");
define("SHOWQRZ", "on");
define("RSSI", "avg");
?>
```

**Comment by s-s-s** [comment]
Ok, now it works )
http://250203.radiocult.ru:8082/html.new/index.php
 To have a switch between mutlimode dmr&dstar, dmr and dstar ,  we need make a several changes.
1. insert buttom for dmr&dstar, dmr and dstar modes into index.php
```
 <button onclick="window.location.href='./scripts/switchnetwork.php?network=BRANDMEISTER'"  type="button" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>&nbsp;<?php echo _("DMR&DSTAR"); ?></button>
  <button onclick="window.location.href='./scripts/switchnetwork.php?network=DMR'"  type="button" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>&nbsp;<?php echo _("DMR only"); ?></button>
  <button onclick="window.location.href='./scripts/switchnetwork.php?network=DSTAR'"  type="button" class="btn btn-default navbar-btn"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>&nbsp;<?php echo _("DSTAR only"); ?></button>

```
2. edit switchnetwork.php to put any new mode 

```
  if ($_GET['network'] == "DMR") {
    setDMRNetwork("DMR");
    exec( "sudo cp ".MMDVMINIPATH."/DMR.ini ".MMDVMINIPATH."/".MMDVMINIFILENAME );
    exec( REBOOTMMDVM );
  }
  if ($_GET['network'] == "DSTAR") {
    setDMRNetwork("DSTAR");
    exec( "sudo cp ".MMDVMINIPATH."/DSTAR.ini ".MMDVMINIPATH."/".MMDVMINIFILENAME );
    exec( REBOOTMMDVM );
  }
  if ($_GET['network'] == "BRANDMEISTER") {
    setDMRNetwork("BrandMeister");
    exec( "sudo cp ".MMDVMINIPATH."/BRANDMEISTER.ini ".MMDVMINIPATH."/".MMDVMINIFILENAME );
    exec( REBOOTMMDVM );
  }
```

3. Make 3 ini-files for each mode: BRANDMEISTER.ini , DMR.ini and DSTAR.ini and put them near with MMDVM.ini

4. Edit networks.php

```
<?php
$networks_json = '{
          "DMR":{
            "label":"Singlemode DMR",
                "ini":"DMR",
                "logo":""
          },
          "BRANDMEISTER":{
            "label":"Multimode BrandMeister",
                "ini":"BRANDMEISTER",
                "logo":""
          },
          "DSTAR":{
            "label":"Singlemode D-STAR",
            "ini":"DSTAR",
            "logo":""
          }
}';

$networks = json_decode($networks_json, true);
?>

```

**Comment by dg9vh** [comment]
Now it should work - names in networks.php are ad libitum - now we absolutely believe in "ini"-Parameter... so you can do also something like that:

"the one guys":{
            "label":"Singlemode DMR",
                "ini":"DMR",
                "logo":""
          },
          "the others guys":{
            "label":"Multimode BrandMeister",
                "ini":"BRANDMEISTER",
                "logo":""
          }

**Comment by dc7jzb** [comment]
Works fine, thanks. 8)
