### ISSUE TITLE
YSF Reflector Status still shows linked

### ISSUE THREAD

**Issue by ve1aic** [dg9vh/MMDVMHost-Dashboard#131]
"YSF linked to" does not seem to update when the Reflector connection is disconnected.
It is still showing Linked To the last Reflector from the YSFGateway.

**Comment by dg9vh** [comment]
Did you reload the page? This Information is not dynamically updated, it updates by reloading the whole page... 

if this also does not help, it's a serious issue ...

**Comment by ve1aic** [comment]
Yes, reloaded dashboard page..tried another browser..tried my cell phone on outside network. All the same, still showing connected to "CA" Reflector despite being disconected more than 2 hours ago.
http://c4fmontario.hopto.org/

**Comment by ve1aic** [comment]
You can monitor my repeater dashboard here:

http://ve1aic.no-ip.com:81

73, Ron
VE1AIC

**Comment by dg9vh** [comment]
PSE send me your gateway log...

**Comment by ve1aic** [comment]
Here is YSFGateway log of Activity Timeout Disconnect:

M: 2017-03-22 13:15:13.948 Disconnecting due to inactivity
D: 2017-03-22 13:15:15.949 DISCONNECT Reply
D: 2017-03-22 13:15:15.949 0000:  0A 5D 41 5F 26 39 38 31 35 35 56 45 31 
43 52 41    *.]A_&98155VE1CRA*
D: 2017-03-22 13:15:15.950 0010:  2D 52 20 20 50 45 49 20 43 61 6E 61 64 
61 20 20    *-R  PEI Canada  *
D: 2017-03-22 13:15:15.950 0020:  20 20 31 32 20 20 20 20 20 20 20 20 20 
20 20 20    *  12            *
D: 2017-03-22 13:15:15.950 0030:  20 20 20 20 20 20 20 20 20 30 30 30 20 
20 20 20    *         000    *
D: 2017-03-22 13:15:15.950 0040:  20 20 20 20 20 20 20 20 20 20 20 20 20 
20 20 20    *                *
D: 2017-03-22 13:15:15.950 0050:  20 20 20 20 20 20 20 20 20 03 86 
             *         ..*

------------

Here is manual Disconnect:
(Looks like a typo here 'Disconect')

D: 2017-03-22 12:37:11.790 Received Disconect from VE1AIC-6
M: 2017-03-22 12:37:11.791 Disconnect has been requested by VE1AIC-6
D: 2017-03-22 12:37:13.790 DISCONNECT Reply
D: 2017-03-22 12:37:13.790 0000:  02 5D 41 5F 26 39 38 31 35 35 56 45 31 
43 52 41    *.]A_&98155VE1CRA*
D: 2017-03-22 12:37:13.790 0010:  2D 52 20 20 50 45 49 20 43 61 6E 61 64 
61 20 20    *-R  PEI Canada  *
D: 2017-03-22 12:37:13.791 0020:  20 20 31 32 20 20 20 20 20 20 20 20 20 
20 20 20    *  12            *
D: 2017-03-22 12:37:13.791 0030:  20 20 20 20 20 20 20 20 20 30 30 30 20 
20 20 20    *         000    *
D: 2017-03-22 12:37:13.791 0040:  20 20 20 20 20 20 20 20 20 20 20 20 20 
20 20 20    *                *
D: 2017-03-22 12:37:13.791 0050:  20 20 20 20 20 20 20 20 20 03 7E 
             *         .~*

------------

73, Ron

**Comment by dg9vh** [comment]
Hi Ron, could you please check, if the actual Version would fix your Problem?

Kim

**Comment by ve1aic** [comment]
OK I see you are updating Functions.php to try to catch the DISCONNECT.
That change did not do anything.

FYI, it catches every time when a new REFLECTOR is connected but it does 
not seem to catch the DISCONNECT.

73, Ron
