### ISSUE TITLE
RSSI avg/min/max

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#143]
Hi

in order to evaluate every RF hang, it is usefull to see in the dashboard min/max/avg values of RSSI.
Is is possible to have the three value in the same time ?

thank you

**Comment by phl0** [comment]
Would you please test this code:
https://github.com/phl0/MMDVMHost-Dashboard/tree/MinMaxAvg
I would like to see this working. Do you have an URL to a dashboard where you can test my code?

**Comment by phl0** [comment]
Modification works. Merged into main code.

![bildschirmfoto vom 2017-04-12 14-47-21](https://cloud.githubusercontent.com/assets/7112907/24958295/1f6bc158-1f8f-11e7-990d-f5f314911b1d.png)
