### ISSUE TITLE
Error 500 on latest pull

### ISSUE THREAD

**Issue by m1geo** [dg9vh/MMDVMHost-Dashboard#148]
I have an issue with the Dashboard. I have had it running for a few years and recently it has stopped.

Running Commit #f882cbc127db6e9f3dd859f444f54592e36855d8

Any help would be appreciated.

`
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (ary file /opt/MMDVMHost) at position 0 (a): The timezone could not be found in the database in /opt/MMDVMHost-Dashboard/include/tools.php:111
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /opt/MMDVMHost-Dashboard/include/tools.php(111): DateTime->__construct('ary file /opt/M...')
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /opt/MMDVMHost-Dashboard/include/functions.php(473): convertTimezone('ary file /opt/M...')
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /opt/MMDVMHost-Dashboard/include/functions.php(497): getHeardList(Array, false)
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /opt/MMDVMHost-Dashboard/include/init.php(13): getLastHeard(Array, false)
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /opt/MMDVMHost-Dashboard/index.php(25): include('/opt/MMDVMHost-...')
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr: #5 {main}
2017-04-28 20:08:41: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /opt/MMDVMHost-Dashboard/include/tools.php on line 111
`

George M1GEO

**Comment by dg9vh** [comment]
Hi George, maybe you have to reinstall tzdata again? Seems that the timezone-information is lost.

**Comment by dg9vh** [comment]
Oh, no - there is some other issue - what version of MMDVMHost you are using?

**Comment by dg9vh** [comment]
what page you are calling when this error happens?

The part Failed to parse time string (ary file /opt/MMDVMHost) reads, as it is trying to parse a cutted "no such binary file /opt/MMDVMHost" into a date.
Are you sure, you configured config.php right with the parameter ;
define("MMDVMHOSTPATH", "/path/to/your/MMDVMHost-binary but without MMDVMHost-name");
?

**Comment by m1geo** [comment]
MMDVMHost latest master: #9ac4919

george@repeater:/opt/MMDVMHost$ sudo apt install tzdata
[sudo] password for george: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tzdata is already the newest version (2016j-0ubuntu0.16.04).

Paths are all set correctly; define("MMDVMHOSTPATH", "/opt/MMDVMHost");
They worked correctly about a week ago, from the last year.

Thanks, Kim.
George M1GEO

**Comment by dg9vh** [comment]
did you run setup.php and saved configuration again to write actual config?

**Comment by m1geo** [comment]
Yup: So I have define("MMDVMHOSTPATH", "/opt/MMDVMHost"); and the actual binary is "/opt/MMDVMHost/MMDVMHost".

![screenshot_2017-04-28_21-22-52](https://cloud.githubusercontent.com/assets/758615/25545983/dc767d3a-2c58-11e7-8ff5-838db4cada21.png)

**Comment by dg9vh** [comment]
what happens, if you do on a terminal:
sudo -u www-data /opt/MMDVMHost/MMDVMHost -v
?

**Comment by m1geo** [comment]
This... ;)

`
root@repeater:/opt/MMDVMHost-Dashboard# sudo -u www-data /opt/MMDVMHost/MMDVMHost -v
MMDVMHost version 20170406 git #9ac4919
root@repeater:/opt/MMDVMHost-Dashboard# 
`

**Comment by dg9vh** [comment]
no clue what happens there...
could you send me your MMDVM-Logfile via email? dg9vh@darc.de

**Comment by m1geo** [comment]
Sent, OM.

**Comment by dg9vh** [comment]
Do you have enabled name lookup?
on my test-system with disabled name-lookup your log is running fine...
![image](https://cloud.githubusercontent.com/assets/13950650/25547542/ecb0fb1c-2c67-11e7-89b5-057960aeb09a.png)

Next try is what happens with enabled lookup...

**Comment by dg9vh** [comment]
In my opinion it has to to with the name lookup... so a quick help would be disabling it..

**Comment by m1geo** [comment]
Yes! Disabled name-lookup and it works!
Any idea what the issue is.
PS, sorry for the delay. Thanks Kim.

**Comment by dg9vh** [comment]
Not really an idea.I ll take further investigation on that.Am 29.04.2017 02:27 schrieb George Smart <notifications@github.com>:Yes! Disabled name-lookup and it works!
Any idea what the issue is.
PS, sorry for the delay. Thanks Kim.

**Comment by m1geo** [comment]
Thanks Kim.
I noticed it broke mysteriously a day or so ago, and I just got round to raising the issue :)

**Comment by dg9vh** [comment]
All in all you are the first and actually the only one reporting this
problem... so it happens under very special conditions, it seems.

I studied your logfile from start to end but found nothing that was odd
to me... so we have to see, what comes.



Am Samstag, den 29.04.2017, 00:54 -0700 schrieb George Smart:
> Thanks Kim.
> I noticed it broke mysteriously a day or so ago, and I just got round
> to raising the issue :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 

-- 
Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt!
Ortsverband Q05, Völklingen

**Comment by m1geo** [comment]
No problem, Kim. These things happen, and it's usually me!
I see there are some odd overflows from MMDVM. I'll restart the modem. No problem. Dashboard is _MUCH_ faster without the lookup, so I'll stay as it is.

**Comment by s-s-s** [comment]
Hi! Got the same error after updating the MMDVHost up to build 20170501 
(
