### ISSUE TITLE
rssi not showing on dashboard 

### ISSUE THREAD

**Issue by scotta1980** [dg9vh/MMDVMHost-Dashboard#149]
i cant get the rssi to show on the dashboard is there something i have to do for this to work i am running a motorola gm340 i have the rssi pin connected also have it enabled in the firmware for the mmdvm

**Comment by dg9vh** [comment]
@scotta1980 is the RSSI correctly shown in the MMDVM.log?

**Comment by scotta1980** [comment]
voice transmission, 8.7 seconds, 4% packet loss, BER: 0.0%
M: 2017-05-08 08:16:06.572 DMR Slot 2, received network voice header from MM1BJO to TG 9
M: 2017-05-08 08:16:08.085 DMR Slot 2, network watchdog has expired, 0.1 seconds, 0% packet loss, BER: 0.0%
M: 2017-05-08 10:38:59.056 DMR Slot 2, received network voice header from GM0ROU to TG 9
M: 2017-05-08 10:39:00.303 DMR Slot 2, received network end of voice transmission, 1.2 seconds, 0% packet loss, BER: 1.0%
M: 2017-05-08 10:57:18.578 DMR Slot 2, received RF voice header from MM3LSO to TG 9
M: 2017-05-08 10:57:21.276 DMR Slot 2, received RF end of voice transmission, 2.5 seconds, BER: 2.3%
M: 2017-05-08 10:57:24.811 DMR Slot 2, received RF voice header from MM3LSO to TG 9
M: 2017-05-08 10:57:26.430 DMR Slot 2, received RF end of voice transmission, 1.4 seconds, BER: 0.2%

**Comment by dg9vh** [comment]
@scotta1980 RSSI values are only shown at local transmissions... your MMDVM is not correctly configured to put the RSSI into the log. please check your MMDVM.ini, if the RSSI.dat is correctly configured and check your firmware, if #define SEND_RSSI_DATA is enabled.

**Comment by phl0** [comment]
RSSIMappingFile is the parameter to set in the MMDVM.ini

**Comment by scotta1980** [comment]
thanks fixed now the RSSI.dat file was empty did not have the values working now
