### ISSUE TITLE
D-Star linked 

### ISSUE THREAD

**Issue by YV5OF** [dg9vh/MMDVMHost-Dashboard#15]
Hi Kim,

Today I did the upgrade repository, and test the dashboard observed:

That being connected to a reflector D-Star, not shown in linkto

![captura de pantalla 2016-05-24 a las 1 08 57 p m](https://cloud.githubusercontent.com/assets/19210807/15513458/afe143e2-21b2-11e6-8e00-45a6bd3e6c08.png)

![captura de pantalla 2016-05-24 a las 1 24 10 p m](https://cloud.githubusercontent.com/assets/19210807/15513493/d8ce763a-21b2-11e6-984e-0a4440ecab82.png)

**Comment by dg9vh** [comment]
Had you configured the right path to Link.log?

**Comment by YV5OF** [comment]
Yes, 

My log path is -> define("LOGPATH", "/var/log/opendv/");
define("LINKLOGPATH", LOGPATH . "/Links.log");

Into log path -> May 24 14:15 Links.log

tail -f Links.log 
2016-05-24 18:15:52: DCS link - Type: Repeater Rptr: YV5OF  C Refl: DCS018 D Dir: Outgoing

**Comment by dg9vh** [comment]
If you really have moved to actual version from github, the structure of config.php has moved a little bit:

```
<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

define("MMDVMLOGPATH", "/mnt/ramdisk/");
define("MMDVMLOGPREFIX", "MMDVM");
define("MMDVMINIPATH", "/etc/mmdvm/");
define("MMDVMINIFILENAME", "MMDVM.ini");
define("MMDVMHOSTPATH", "/usr/local/bin/");
define("LINKLOGPATH", "/var/log/");
define("IRCDDBGATEWAY", "ircddbgatewayd");
define("REFRESHAFTER", "60");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("LHLINES", "20");
?>
```

So you have to put only "/var/log/opendv/" into define of LINKLOGPATH

**Comment by YV5OF** [comment]
Uhmmm, ok try remove all directory and clone repository.

**Comment by dg9vh** [comment]
you can also call setup.php to get a little configurator

**Comment by YV5OF** [comment]
Done Kim,

Remove all file on /var/www/html/
Cloning repository again.
And install from setup.php

Thank for your time.

![captura de pantalla 2016-05-24 a las 2 40 56 p m](https://cloud.githubusercontent.com/assets/19210807/15515732/8fde44f4-21bd-11e6-9c83-0ea71f57f07b.png)

**Comment by dg9vh** [comment]
Yessss :+1:

**Comment by ve1aic** [comment]
1. Newest version of Dashboard gives me many errors.
   
   Using the latest version "Commits on May 22, 2016 " gives the errors 
   below in your current dashboard.
   FYI I replaced all dashboard files and re-edited config.php just in  case.
2. Is there a way to view the YSF reflector setting now that its available.
   [System Fusion Network]
   Enable=1
   #Address=127.0.0.1
   Address=c4fm.duckdns.org
   Port=42000
   Debug=0

73, Ron
VE1AIC
My error log from today:

[Wed May 25 09:10:00.572979 2016] [:error] [pid 17617] [client 
192.168.1.105:50068] PHP Notice:  Undefined offset: 1 in 
/var/www/html/include/functions.php on line 43
[Wed May 25 09:10:00.573197 2016] [:error] [pid 17617] [client 
192.168.1.105:50068] PHP Notice:  Undefined offset: 1 in 
/var/www/html/include/functions.php on line 50
[Wed May 25 09:10:00.573746 2016] [:error] [pid 17617] [client 
192.168.1.105:50068] PHP Fatal error:  Uncaught exception 'Exception' 
with message 'DateInterval::__construct(): Unknown or bad format (PTS)' 
in /var/www/html/include/functions.php:271\nStack trace:\n#0 
/var/www/html/include/functions.php(271): 
DateInterval->__construct('PTS')\n#1 
/var/www/html/include/repeaterinfo.php(15): getActualMode(Array, 
Array)\n#2 /var/www/html/index.php(42): 
include('/var/www/html/i...')\n#3 {main}\n  thrown in 
/var/www/html/include/functions.php on line 271

**Comment by dg9vh** [comment]
@ve1aic Hi, at 2.: see https://github.com/dg9vh/MMDVMHost-Dashboard/issues/16 for separate tracking...

at 1: could you post me your config.php?

**Comment by dg9vh** [comment]
@ve1aic could you try to add 

> date_default_timezone_set('UTC');

into your config.php (at first line after the comments in header)?

**Comment by ve1aic** [comment]
I just tried again using your setup.php same results. The config.php has the default UTC your mention on line 2.
The "undefined offset " errors have been there since May18th..so not sure what version of Host caused that. However the fatal error in the latest dashboard is:
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateInterval::__construct(): Unknown or bad format (PTS)' in /var/www/html/include/functions.php:271\nStack trace:\n#0 /var/www/html/include/functions.php(271): DateInterval->__construct('PTS')\n#1 /var/www/html/include/repeaterinfo.php(15): getActualMode(Array, Array)\n#2 /var/www/html/index.php(42): include('/var/www/html/i...')\n#3 {main}\n  thrown in /var/www/html/include/functions.php on line 271
------------------\
OK I'm using the git Issue page now instead of email.

**Comment by dg9vh** [comment]
@ve1aic Could you post your [General]-section from MMDVM.ini?
Line 271 is playing around with ModeHang-Value so maybe there is our problem...

Using git issues makes it easier for me to track issues before they get lost in my inbox that is filled up with 100 e-mails when not online for a day... toooooo many projects where my fingers are in, hi.

**Comment by ve1aic** [comment]
OK, setup.php had problems with permissions, gave 666 to config.php and it wrote to it ok.
<?php

# This is an auto-generated config-file!

# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("MMDVMLOGPATH", "/home/host/");
define("MMDVMLOGPREFIX", "");
define("MMDVMINIPATH", "/home/host/");
define("MMDVMINIFILENAME", "");
define("MMDVMHOSTPATH", "/home/host/");
define("LINKLOGPATH", "");
define("IRCDDBGATEWAY", "ircddbgateway");
define("REFRESHAFTER", "");
define("TEMPERATUREHIGHLEVEL", "");
define("LHLINES", "");
?>

**Comment by ve1aic** [comment]
My General section of MMDVM.ini
[General]
Callsign=VE1CRA
Timeout=180
Duplex=1
ModeHang=5
Display=None
Daemon=0

**Comment by dg9vh** [comment]
Seems you missed to fill out some fields like 
define("MMDVMLOGPREFIX", "");
define("MMDVMINIFILENAME", "");
define("LINKLOGPATH", "");
define("REFRESHAFTER", "");
define("TEMPERATUREHIGHLEVEL", "");
define("LHLINES", "");

Looks to me to improve setup.php with checkings of values...

**Comment by ve1aic** [comment]
OK so you have to enter ALL fields, even ones that have the default (in grey)?

**Comment by dg9vh** [comment]
@ve1aic Permissions are mentioned in https://github.com/dg9vh/MMDVMHost-Dashboard/blob/master/linux-step-by-step.md point 3...
It's working perfectly after giving www-data write-permissions

**Comment by dg9vh** [comment]
@ve1aic Yes... sorry, it's a bit misunderstanding there. When back from QRL today in just 1h I'll fix this with some checkings to not get empty values...

**Comment by ve1aic** [comment]
OK, after entering ALL fields using setup.php it works. Writes a new config.php although defined vars are not all same as original config.php from source.

The status page displays ok but the 'offset' errors continue.
 PHP Notice:  Undefined offset: 4 in /var/www/html/include/functions.php on line 144

(offsets 3 & 4 on lines 136 & 144)

**Comment by dg9vh** [comment]
@ve1aic please check with actual commits...

**Comment by ve1aic** [comment]
Just cloned the latest, nice to see YSF Master info.
...oops forgot to verify error log timestamp.
Php 'Offset'  errors have stopped.

**Comment by ve1aic** [comment]
OK error seems to have gone after the last clone.
Keeping an eye on it.
