### ISSUE TITLE
Dashboard Issues

### ISSUE THREAD

**Issue by cwfuselier** [dg9vh/MMDVMHost-Dashboard#150]
The D-Star link status is not changing when I link to a reflector on the Mmdvm Host Dashboard. The ircDDB shows it linked just not the dashboard? I am running the KB5RAB mmdvm image.

**Comment by dg9vh** [comment]
What github-version is shown in the footer? Is it current version?Am 14.05.2017 05:10 schrieb cwfuselier <notifications@github.com>:The D-Star link status is not changing when I link to a reflector on the Mmdvm Host Dashboard. The ircDDB shows it linked just not the dashboard? I am running the KB5RAB mmdvm image.

**Comment by dg9vh** [comment]
@cwfuselier sorry, I can't reproduce it with current version. Must be an issue with pre-released versions. Please update to current version.

**Comment by cwfuselier** [comment]
I should be running the current version. It says mmdvm-host-dashboard V. 20170429-1

**Comment by cwfuselier** [comment]
Ok updated the dashboard with same problem. Shows in the last heard just said not linked in the repeater status. Dmr and fusion work great just not the D-Star side. Can send a pic of the screen.

**Comment by phl0** [comment]
Please attach the screenshot. 
Are there any errors in the log of the web server?

**Comment by dg9vh** [comment]
Has DStar link indicator ever worked correctly? Am 15.05.2017 03:58 schrieb cwfuselier <notifications@github.com>:Ok updated the dashboard with same problem. Shows in the last heard just said not linked in the repeater status. Dmr and fusion work great just not the D-Star side. Can send a pic of the screen.

**Comment by cwfuselier** [comment]
Ok will send when i get of work and home. I believe its never worked and i am not receiving any error as I know of. Will let you know in a few.

**Comment by cwfuselier** [comment]
Here are the Images that i have. Let me know if you need something else. 
![20170516_002602](https://cloud.githubusercontent.com/assets/24363278/26091281/d770a4da-39cf-11e7-92dd-142f81f0ffe3.jpg)
![20170516_002713](https://cloud.githubusercontent.com/assets/24363278/26091282/d9538d8a-39cf-11e7-8cf2-5f69059b9e32.jpg)
![20170516_002930](https://cloud.githubusercontent.com/assets/24363278/26091284/da77bcd6-39cf-11e7-8e85-6bed6272711f.jpg)

**Comment by dg9vh** [comment]
Please send me your config.php via email to DG9VH at darc. De

**Comment by cwfuselier** [comment]
ok ill have to find it. don't to see it in the dashboard directory. Unless you know where it is located at?

**Comment by cwfuselier** [comment]
Sent.

**Comment by dg9vh** [comment]
In the Dashboard folder in subfolder configAm 16.05.2017 16:52 schrieb cwfuselier <notifications@github.com>:ok ill have to find it. don't to see it in the dashboard directory. Unless you know where it is located at?

**Comment by dg9vh** [comment]
Source found - problem not in Dashboard, problem lies in ircddbgateway configuration. /var/log/opendv/Links.log is empty because no gui-log enabled in config... therefore closed here...
