### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by m1geo** [dg9vh/MMDVMHost-Dashboard#151]
Hi Again, Folks.

I still keep seeing Error 500 from the MMDVMHost-Dashboard at GB7KH: http://gb7kh.co.uk:4040/mmdvm/

The lighttpd server gives the following error:

>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (ary file /opt/MMDVMHost) at position 0 (a): The timezone could not be found in the database in /opt/MMDVMHost-Dashboard/include/tools.php:111
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /opt/MMDVMHost-Dashboard/include/tools.php(111): DateTime->__construct('ary file /opt/M...')
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /opt/MMDVMHost-Dashboard/include/functions.php(476): convertTimezone('ary file /opt/M...')
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /opt/MMDVMHost-Dashboard/include/functions.php(497): getHeardList(Array, false)
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /opt/MMDVMHost-Dashboard/include/init.php(13): getLastHeard(Array, false)
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /opt/MMDVMHost-Dashboard/index.php(25): include('/opt/MMDVMHost-...')
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr: #5 {main}
>2017-05-17 18:33:15: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /opt/MMDVMHost-Dashboard/include/tools.php on line 111

Attached is a PDF of the log for today. This happens quite often. Some days the dashboard works. Other times, such as today with the attached log, it does not. [gb7kh_log_mmdvm.pdf](https://github.com/dg9vh/MMDVMHost-Dashboard/files/1008651/gb7kh_log_mmdvm.pdf)

Also including `config.php`:

>This is an auto-generated config-file!
>Be careful, when manual editing this!
>date_default_timezone_set('UTC');
>define("MMDVMLOGPATH", "/opt/MMDVMHost");
>define("MMDVMINIPATH", "/opt/MMDVMHost");
>define("MMDVMINIFILENAME", "MMDVM.ini");
>define("MMDVMHOSTPATH", "/opt/MMDVMHost");
>define("TALKERALIAS", "on");
>define("DMRIDDATPATH", "/opt/MMDVMHost/DMRIds.dat");
>define("ENABLEYSFGATEWAY", "on");
>define("YSFGATEWAYLOGPATH", "/opt/YSFClients/YSFGateway");
>define("YSFGATEWAYLOGPREFIX", "YSFGateway");
>define("YSFGATEWAYINIPATH", "/opt/YSFClients/YSFGateway");
>define("YSFGATEWAYINIFILENAME", "YSFGateway.ini");
>define("YSFHOSTSPATH", "/opt/YSFClients/YSFGateway");
>define("YSFHOSTSFILENAME", "YSFHosts.txt");
>define("LINKLOGPATH", "/var/log/opendv");
>define("IRCDDBGATEWAY", "ircddbgatewayd");
>define("TIMEZONE", "Europe/London");
>define("LOCALE", "en_GB");
>define("LOGO", "https://www.george-smart.co.uk/wordpress/wpcontent/uploads/2015/12/LogoWide.png");
>define("DMRPLUSLOGO", "");
>define("BRANDMEISTERLOGO", "https://wiki.brandmeister.network/images/brandmeister.png"
>define("REFRESHAFTER", "180");
>define("SHOWRPTINFO", "on");
>define("SHOWMODES", "on");
>define("SHOWLH", "on");
>define("SHOWLOCALTX", "on");
>define("SHOWPROGRESSBARS", "on");
>define("TEMPERATUREALERT", "on");
>define("TEMPERATUREHIGHLEVEL", "60");
>define("SWITCHNETWORKUSER", "");
>define("SWITCHNETWORKPW", "");
>define("VIEWLOGUSER", "");
>define("VIEWLOGPW", "");
>define("HALTUSER", "");
>define("HALTPW", "");
>define("REBOOTUSER", "");
>define("REBOOTPW", "");
>define("RESTARTUSER", "");
>define("RESTARTPW", "");
>define("REBOOTMMDVM", "");
>define("REBOOTSYS", "");
>define("HALTSYS", "");
>define("POWERONLINEPIN", "");
>define("POWERONLINESTATE", "");
>define("SHOWQRZ", "on");
>define("RSSI", "avg");

Second time I've reported this issue, previously reported as Issue #148 

George M1GEO

**Comment by dg9vh** [comment]
@m1geo this issue happens, if the log-file grows to big. what loglevel do you have set in MMDVM.ini for FileLog? It is recommended to put it to 2 - and also it would be better to disable "debug" to make the logfile as small as possible. This is also a performance-issue.

**Comment by m1geo** [comment]
As requested, an excerpt from `error.log`

> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (ary file /opt/MMDVMHost) at position 0 (a): The timezone could not be found in the database in /opt/MMDVMHost-Dashboard/include/tools.php:111
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: Stack trace:
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #0 /opt/MMDVMHost-Dashboard/include/tools.php(111): DateTime->__construct('ary file /opt/M...')
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #1 /opt/MMDVMHost-Dashboard/include/functions.php(472): convertTimezone('ary file /opt/M...')
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #2 /opt/MMDVMHost-Dashboard/include/functions.php(493): getHeardList(Array, false)
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #3 /opt/MMDVMHost-Dashboard/include/init.php(13): getLastHeard(Array, false)
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #4 /opt/MMDVMHost-Dashboard/index.php(25): include('/opt/MMDVMHost-...')
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr: #5 {main}
> 2017-07-04 13:16:15: (mod_fastcgi.c.2695) FastCGI-stderr:   thrown in /opt/MMDVMHost-Dashboard/include/tools.php on line 111

**Comment by m1geo** [comment]
From `MMDVM.ini`

[Log]
\# Logging levels, 0=No logging
DisplayLevel=2
FileLevel=2
FilePath=.
FileRoot=MMDVM

All debug are 0.

**Comment by m1geo** [comment]
Looks also related/same as #148

**Comment by dg9vh** [comment]
can't reproduce with your current log... see http://db0ew.darc-saar.de - there I copied your log into a file and changed MMDVM.ini to push the log into the dashboard...

**Comment by dg9vh** [comment]
Only thing I must admit is, that creating the page takes a very long time (about 1 minute). What hardware are you running on? Raspi 3? Or below?

**Comment by m1geo** [comment]
It's running on a SuperMicro A1SRM-LN7F/LN5F 19" rack machine with Intel(R) Atom(TM) CPU  C2358  @ 1.74GHz, 4GB RAM. `uname -a`:

> Linux gb7kh 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

It's running Ubuntu 16.04.2 LTS with `lighttpd` as the web server.

**Comment by dg9vh** [comment]
Still persisting? I got reports of setting the timeout for scripts in php.ini to values like 120 seconds or more would solve this...

If still persisting after changeing php.ini reopen this.
