### ISSUE TITLE
Why it does not show "MMDVMHost by G4KLX Version"?

### ISSUE THREAD

**Issue by gigalamer** [dg9vh/MMDVMHost-Dashboard#152]
Why it does not show "MMDVMHost by G4KLX Version"?

root@raspi:/opt/MMDVMHost# ./MMDVMHost --version
MMDVMHost version 20170501 git #ed93628
but, on the dashboard is empty.

As you can see on http://goodbyte.no-ip.biz/
probably misconfig, but I don`t know where.

**Comment by dg9vh** [comment]
Hi, where is your MMDVMHost located in the Filesystem and could you post your config.php without any passwords here?

**Comment by gigalamer** [comment]
Hi.
Uuuhhh. Just found it.
I'm sorry to bother you.
