### ISSUE TITLE
enable setup.php to tidy up inputs from unwanted characters

### ISSUE THREAD

**Issue by dh3wr** [dg9vh/MMDVMHost-Dashboard#154]
Just generated config.php:
````
<?php
# This is an auto-generated config-file!
# Be careful, when manual editing this!

date_default_timezone_set('UTC');
define("MMDVMLOGPATH", "/var/log/MMDVMHost/"");
define("MMDVMINIPATH", "/home/pi/"");
````
Double ``"`` at the end of two lines

**Comment by dh3wr** [comment]
My error, C&P from the old file got the ``"`` into the web form

**Comment by dg9vh** [comment]
@dh3wr I would add some additional checkings and clean-up-functionalities to tidy up the input :-)

**Comment by dg9vh** [comment]
just keep the door open as reminder...
