### ISSUE TITLE
Move to websockets instead of polling

### ISSUE THREAD

**Issue by dh3wr** [dg9vh/MMDVMHost-Dashboard#155]
I see with 2 instances of the Dashboard open in Browser 45 % CPU load on a Pi3 from the apache. I think it's from the 1 sec. polling ajax. I know it's not that easy but maybe switching to websockets would be cool to have event triggered updates?

**Comment by dg9vh** [comment]
actually investigating how to do this - never worked with websockets before :-)

**Comment by dh3wr** [comment]
Checkout https://github.com/dh3wr/RasPagerDigi/tree/master/software/Simple-WebSocket-Server . You need in thsi case a C++ Programm providing the information via Websocket to a JS-enabled website.
