### ISSUE TITLE
Dashboard ... web server data update

### ISSUE THREAD

**Issue by i8ulu** [dg9vh/MMDVMHost-Dashboard#156]
I ask Kim, who is the author, but also to anyone who can help me solve the problem on the local weserver dashboard of my hotspot. After updating the latest version, a very long wait time for updating data with the browser (about 60 sec), while with the old version is immediate. I wonder if there is a remedy for this problem.
  Thanks de Giacomo i8ulu

**Comment by phl0** [comment]
Please name the git commit ID of the version that was known working and the ID that causes the long delay. Also please let us know if you have enabled extended name lookups.

**Comment by i8ulu** [comment]
Thanks for the ID answer is 8e23051 - I also insert the dashboard link for any verification - (http://i8ulu.dynalias.com:81/).


  Thanks again 73 Giacomo i8ulu

**Comment by dg9vh** [comment]
Host not reachable...-- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 08.07.2017 10:06 schrieb Giacomo Palumbo <notifications@github.com>:Thanks for the ID answer is 8e23051 - I also insert the dashboard link for any verification - (http://i8ulu.dynalias.com:81/).
  Thanks again 73 Giacomo i8ulu

**Comment by i8ulu** [comment]
Host is active but updates after 60 sec. While the old version is all ok. 
old: (http://i8ulu.dynalias.com:82/index.php) New: (http://i8ulu.dynalias.com:81/index.php).

  Thanks anyway for the answer.

**Comment by dg9vh** [comment]
Old Version is not loading, new version is no actual release...-- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 08.07.2017 15:29 schrieb Giacomo Palumbo <notifications@github.com>:Host is active but updates after 6 sec. While the old version is all ok.
old: (http://i8ulu.dynalias.com:82/index.php) New: (http://i8ulu.dynalias.com:81/index.php).
  Thanks anyway for the answer.

**Comment by dg9vh** [comment]
See screenshot attached.-- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 08.07.2017 15:29 schrieb Giacomo Palumbo <notifications@github.com>:Host is active but updates after 6 sec. While the old version is all ok.
old: (http://i8ulu.dynalias.com:82/index.php) New: (http://i8ulu.dynalias.com:81/index.php).
  Thanks anyway for the answer.

**Comment by i8ulu** [comment]
Ok - Thanks again for the great work it is doing for the radio community - 73

**Comment by dg9vh** [comment]
may you should try a git pull and fetch a recent version of the dashboard and then try again...actual official version is: MMDVMHost-Dashboard V 20170516-1 (GitID #c24b9af) which is quite a month later than the version running on your system. now your older version also responding...  Maybe you have some additional info from webserver's error.log? if there is any?

**Comment by i8ulu** [comment]
Thanks Kim for good suggestions, I made the Git but no switchnet and switcreflector cleaners are active. Anyway, it's okay now. Thank you for all the valuable support you are giving us.
  73
