### ISSUE TITLE
It does not work on my platform

### ISSUE THREAD

**Issue by Power-Extreme** [dg9vh/MMDVMHost-Dashboard#159]
Hi,
  i have an orange pi one and with image from https://www.armbian.com/ (Command line interface – server usage scenario). I install MMDVMHost put MMDVMHost-Dashboard and not work. Please help.

**Comment by dg9vh** [comment]
Please provide more info. What exactly does not work? what's the webservers error.log about this? Maybe provide some screenshots.

**Comment by Power-Extreme** [comment]
Do you want to go in and see for yourself? 46.10.123.106

**Comment by dg9vh** [comment]
looks like that the ini-files etc. are not readable by webserver-user... please make the folders and files readable for your webserver-user

**Comment by Power-Extreme** [comment]
user: root
pass:help

**Comment by dg9vh** [comment]
this is public available, you know? everybody can read... and I don't have time to visit each system that is not working. please make a "sudo chmod -R og+r /root/MMDVMHost" by your own...

**Comment by Power-Extreme** [comment]
I open only for you. I really do not know what to do. not working.

**Comment by Power-Extreme** [comment]
OK thanks. I reinstal everything and try it again. Thanks a lot for your attention.
