### ISSUE TITLE
Integration of custom content

### ISSUE THREAD

**Issue by phl0** [dg9vh/MMDVMHost-Dashboard#164]
It would be useful if the dashboard would have an option to include a custom file that the user can fill with user defined content. For example displaying some graphs with temperature data of the system the dashboard is running on. 
Example:

![screenshot from 2017-10-12 14-12-35](https://user-images.githubusercontent.com/7112907/31495344-9253d68a-af57-11e7-978b-d33d56b68cec.png)

**Comment by phl0** [comment]
Currently testing in separate branch https://github.com/dg9vh/MMDVMHost-Dashboard/tree/customcontent

**Comment by dg9vh** [comment]
If it is possible for me, I would give it a try but I don't think, that you made big errors within this :-)

**Comment by phl0** [comment]
Has been merged into master with cd178e433e93ffe2a78d59615aa9cd41a5b9cc1f
