### ISSUE TITLE
Log file/display in Local time rather than UTC

### ISSUE THREAD

**Issue by yo6nam** [dg9vh/MMDVMHost-Dashboard#166]
Assumed it's a MMDVMHost issue but it's Dashboard related. All details here : 
https://github.com/g4klx/MMDVMHost/issues/334

Thanks

**Comment by dg9vh** [comment]
This is for internal usage for me:
Idea: Problem sits in using system-timezone instead UTC when creating filename for log-files... 
Solution: Try to convert local system time to UTC and use this to create filenames...

I would check, if I could find some time this evening to try this out...

**Comment by dg9vh** [comment]
actual hotfix: let the system run in utc and configure correct timezone in dashboard to see correct times...
