### ISSUE TITLE
Network Switch / Reflector buttons not working

### ISSUE THREAD

**Issue by vector603** [dg9vh/MMDVMHost-Dashboard#168]
I am having difficulty getting the buttons to switch networks and reflectors and restart the MMDVM host working.  Clicking on them doesn't appear to have any effect on MMDVMhost

Here is a log sample:

[LogSample.txt](https://github.com/dg9vh/MMDVMHost-Dashboard/files/1642596/LogSample.txt)

**Comment by dg9vh** [comment]
Please give me your networks.php file here. There must be something odd within this.

**Comment by vector603** [comment]
I forgot to update the ticket... I was able to resolve the issue... The permissions were incorrect. I updated the permissions and all is working.

Thanks

Ryan
