### ISSUE TITLE
DMRIDs.dat not correct

### ISSUE THREAD

**Issue by darrell24015** [dg9vh/MMDVMHost-Dashboard#172]
I enabled the cron job exactly as described in the README and the moved the shell scripts.  Two things are happening 1) the script is running every minute and 2) I keep getting this in the Dashboard  

> DMRIDs.dat not correct!

I would suggest for the crontab to use
`30 */24 * * *`

Not sure why I'm getting the DMRIDs.dat not correct though.  Thanks in advance for your help.

**Comment by phl0** [comment]
What is the content of DMRIDs.dat after a run by the cron job. And does
the job really run?

**Comment by darrell24015** [comment]
The cron job does run ... here's a sample of the content in the DMRIds.dat file
`31000 W2WDW Dean
31001 N0EUG John
31002 W0PM John
31003 K0ACM Art`

**Comment by darrell24015** [comment]
Not sure why this problem existed, but deleted current install and started over.
