### ISSUE TITLE
Calls don't display in dashboard

### ISSUE THREAD

**Issue by f1iwq** [dg9vh/MMDVMHost-Dashboard#177]
Hello !!
I got an issue with the last version, as it doesn't display any call in the "Call heard heard today list",
nor the "local list transmission".

Both of the SHOWLH and SHOWLOCALTX are set to "ON" in the config.php
DMRIds.dat is up to date, and the call list is not empty as it display the current call on the top.

Any idea?!

73 and thks

**Comment by dg9vh** [comment]
No idea at the moment. What is shown instead? Take also a look at the MMDVMHost log. -- Amateurfunk ist das, was uns verbindet! Bleiben wir in Kontakt! Ortsverband Q05, VölklingenAm 22.05.2018 18:14 schrieb f1iwq <notifications@github.com>:Hello !!
I got an issue with the last version, as it doesn't display any call in the "Call heard heard today list",
nor the local list transmisison.
Both of the SHOWLH and SHOWLOCALTX are set to on in the config.php
DMRIds.dat is up to date
Any idea?!
73 and thks

**Comment by f1iwq** [comment]
Thks for the reply. the list is just empty. I think i've found the problem as it works on another webbowser.
So good news, the issue was NOT the dashboard but the web browser.  
73
