### ISSUE TITLE
Problem switching YSFreflector

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#183]
Hi dear

I'm not able to swtich the YSFReflector, the message in dashboard seems done but the reflector doesn't change and YSF linked to, doesn't write the current reflector
Could you help me please ?
thank you
73

**Comment by dg9vh** [comment]
Hi,
you have to put several lines into /etc/sudoers to get the switching running...  you need /bin/sed and the command you set to restart your YSFGateway.

**Comment by iw9grl** [comment]
do you have an example ? thank you so much

**Comment by dg9vh** [comment]
No sorry... I actually have no productive system running the dashboard with this feature set on...

**Comment by dg9vh** [comment]
take a look at the switching-network-howto to see how to do it in general.

**Comment by iw9grl** [comment]
thank you so much

**Comment by iw9grl** [comment]
Sorry for a new reply :)  I'm not able to see in dashboard, the current YSF linked, the dash says alway : not linked ..... could you help me please ?

tnx

**Comment by dg9vh** [comment]
Do you use the current version of the dashboard?

**Comment by iw9grl** [comment]
YES ... the last one ( sorry for late answer )

**Comment by dg9vh** [comment]
As I said, sorry, I do not have a test-system actually for testing this function, but it worked properly and never was changed since then...

**Comment by dg9vh** [comment]
is this problem persisting? then reopen this, else i close it now
