### ISSUE TITLE
POCSAG Dapnetgateway

### ISSUE THREAD

**Issue by iw2gob** [dg9vh/MMDVMHost-Dashboard#185]
Hi, are you planning to add POCSAG by Dapnetgateway logs ?

Thank you,

73, Maurizio IW2GOB

**Comment by dg9vh** [comment]
Sorry I actually have no time for doing this. Maybe another one finds time for this?

**Comment by iw2gob** [comment]
Thank you Kim, I hope someone could add POCSAG to the dashboard. 73, Maurzio IW2GOB

**Comment by dg9vh** [comment]
I am starting with implementing some basics now... I saw Andrew's doing some good stuff in pi-star, so maybe I grab some ideas there... we'll see.

**Comment by dg9vh** [comment]
I now finished doing first stepps showing messages and actual mode with my solution... so grab actual Dashboard version...

this is now closed.
