### ISSUE TITLE
 failed to open stream: No such file or directory in /var/www/html/setup.php

### ISSUE THREAD

**Issue by ghost** [dg9vh/MMDVMHost-Dashboard#187]
Dear,
trying to open setup.php I have these errors:

`
Warning: include(config/config.php): failed to open stream: No such file or directory in /var/www/html/setup.php on line 2

Warning: include(): Failed opening 'config/config.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/setup.php on line 2`

similar error for main page:

`MMDVMHost by G4KLX Version: 
Firmware: 
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/html/include/functions.php on line 56

Warning: fopen(/tmp/MMDVMFirmware.txt): failed to open stream: No such file or directory in /var/www/html/include/functions.php on line 72

Warning: filesize(): stat failed for /tmp/MMDVMFirmware.txt in /var/www/html/include/functions.php on line 73

Warning: fread() expects parameter 1 to be resource, boolean given in /var/www/html/include/functions.php on line 73`

thanks,

Ivan

**Comment by ghost** [comment]
and trying to save for generating config.php:
Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.25 (Debian) Server at 172.18.0.2 Port 80

**Comment by dg9vh** [comment]
this is an unusual error. The warnings are not serious and the cause is that there is actually no config.php on the system...

But this URI too long is unusual and you are the first one reporting this problem. I think you should give more verbose info about the system you are installing on. What Webserver, what php-version, what OS?

73
Kim

**Comment by ghost** [comment]
Dear thanks for your fast reply!
I am using this [https://github.com/f4hlv/mmdvm-docker](url)

The url too long is related to the fact that each form has this entry: 

<br /><b>Warning</b>:  constant(): Couldn't find constant MMDVMLOGPATH in <b>/var/www/html/setup.php</b> on line <b>79</b><br />

**Comment by ghost** [comment]
But
[ https://github.com/f4hlv/mmdvm-docker](url) is completely broken.
The log between various docker container not crossmounted as volume so the dashboard cannot read MMDVM logs etc etc...
I close the ticket since is not your dashboard the problem I suppose.
Thanks for your time,

Ivan

**Comment by ghost** [comment]
Closed! :-)
