### ISSUE TITLE
TG Names 

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#190]
Hello.
In the dashboard of my IR4UAV system I have enabled the function of displaying the names of the TG, but only some of them are shown.
Where is the file of names to be associated with the TG. 
My DMRIDs.DAT file is correctly read from the dashboard, but I think the names are taken from some other file.

Thank you

![tgs](https://user-images.githubusercontent.com/29512684/57988766-2bca4180-7a92-11e9-9aa6-257919727a8a.jpg)

**Comment by dg9vh** [comment]
Take a look at https://github.com/dg9vh/MMDVMHost-Dashboard/blob/master/database/tgs.csv

You can simply add missing TGs there (and maybe make a pull request :-)

73 de Kim
DG9VH

**Comment by ik4nzd** [comment]
Hi Kim.

Tnx for reply.

unfortunately it does not work

In TGs.csv have this line

"IT","22241","Emilia Romagna","LH  Hoseline  Wiki"

In DMRIds.dat have this line

22241 Emilia_Romagna

In dashboard have this

2019-05-20 18:35:23 DMR Slot 2 IK4NZD Ik4nzd TG EMILIA_ROMAGNA (Name)

where am I wrong?

**Comment by dg9vh** [comment]
Hi, 
the problem could be caused by your double-Entry in the DMRIDs.dat - try it with removing the entry from the dat-file.

73 de Kim
DG9VH

**Comment by ik4nzd** [comment]
Hi Kim.
      You are right, if the TG number is present both in the TGs.CSV and in the DMRIds.dat, then the system presents

      TG EMILIA_ROMAGNA (Name)

      If I remove the TG number from the DMRIds.dat, then I read on the dashboard

      TG 22241 (Emilia_Romagna)

      The only thing I don't understand is related to the fact of the TG TAC-ITA, which are present in both files, but are regularly seen on the dashboard.

      TG TAC4-ITA (TAC4-ITA)

      I had also added the TG to the DMRIDs.dat file through a weekly merge, in order to have the TG name in the MMDVM log ...... like this

      M: 2019-05-20 17:28:24.693 DMR Slot 2, received RF voice header from IK4NZD to TG EMILIA_ROMAGNA

      However, there remains only the question of why with the tactical TG, present in both files, everything works, and with the other TG no .....

      M: 2019-05-20 17:33:32.739 DMR Slot 2, received RF voice header from IK4ANJ to TG TAC4-ITA DMR Slot 2 IK4ANJ IK4ANJ  TG TAC4-ITA (TAC4-ITA) 

2019-05-20   19:33:32    DMR Slot 2    IK4ANJ    IK4ANJ   TG TAC4-ITA (TAC4-ITA)
Have you an idea?
Tnx
‘73 de Adam, IK4NZD
Kim - DG9VH 
Sent: Monday, May 20, 2019 7:11 PM
To: dg9vh/MMDVMHost-Dashboard 
Cc: ik4nzd ; Author 
Subject: Re: [dg9vh/MMDVMHost-Dashboard] TG Names (#190)

Hi,
the problem could be caused by your double-Entry in the DMRIDs.dat - try it with removing the entry from the dat-file.

73 de Kim
DG9VH

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by dg9vh** [comment]
No real idea, sorry...
