### ISSUE TITLE
cpu load & temperature problem

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#191]
On the dashboard installed on my MMDVM system that uses raspberry PI3, I have always had problems with CPU overload (over 60%) and system temperature rising up to 80 °, when I keep the dashboard open in display.
If the dashboard is not displayed by anyone, the CPU load is very low and the temperature remains normal.
After several tests, I realized that the problem occurs when the "Enable extended lookup (show names)" function is active in the dashboard; if this function is not enabled, CPU load and temperature remain normal.
To try to solve the problem, I tried to move the DMRIds.dat file to various folders, in /home/pi , in /var/www/html , in /home, but unfortunately nothing has changed.
If I delete the DMRIds.dat file, the dashboard does not find the file and all values ​​are normal.
How can I solve the problem without risking burning my raspberry, still keeping the Names enabled on the dashboard?
Thanks in advance
Adam, IK4NZD

**Comment by dg9vh** [comment]
You can disable the name resolving function in the dashboard or try to use the sqlite-database for the resolving.

**Comment by ik4nzd** [comment]
Hi Kim, tnx for reply.
I would like to try using sqlite.
I edited the dbupdate.sh file with the latest changes on the site, but if I try to run it I get these errors

pi@ir4uav:/var/www/html/database $ sudo sh dbupdate.sh
Downloading DMR-IDs from RadioID database
Removing IDs from local database
Error: near line 1: near "-": syntax error
inserting new ID-list into local database
Error: incomplete SQL: -e .separator ";"
.import dmrids.dat callsign

Do these errors lead to malfunctions?
However, the dmrids.dat file is created in the folder which has records like these inside:


1023001;VE3THW;
1023002;VA3ECM;
1023003;VE3QC;
1023004;VE3LDY;
1023005;VE3JFN;
1023006;VA3UZ;
1023007;VA3BOC;
1023008;VE3JMR;
1023009;VA3AMO;


I would also like to ask you if the system finds the dmrids.dat file by itself, and therefore I can also not declare the path of the DMRIds.dat in the setup .....

Tnx again.

‘73 de Adam, IK4NZD

**Comment by dg9vh** [comment]
Hi,

I think I should check the update-script - there could be some changes in the format of the data or something else.

The Dashboard is not detecting the location by itself, if you are using the dat-file, you have to give it's complete path including filename (for example /etc/MMDVM/DMRIDs.dat) in the corresponding field in setup.php.

73 de Kim

**Comment by ik4nzd** [comment]
Hi Kim.
I modified the dbupdate.sh file this way

------------------------------------
#!/bin/bash

echo Downloading DMR-IDs from RadioID database
#curl 'https://www.ham-digital.org/status/users.csv' 2>/dev/null | sed -e 's/\t//g' | awk -F"," '/,/{gsub(/ /, "", $
wget 'https://ham-digital.org/status/dmrid.dat' 2>/dev/null > dmrids.dat

echo Removing IDs from local database
printf 'delete from callsign where 1;' | sqlite3 callsigns.db

echo inserting new ID-list into local database
printf '.separator ";" \n.import dmrids.dat callsign' | sqlite3 callsigns.db

---------------------------

Now when I run, I do not detect more errors

----------------------------

pi@ir4uav:/var/www/html/database $ sudo sh dbupdate.sh
Downloading DMR-IDs from RadioID database
Removing IDs from local database
inserting new ID-list into local database

----------------------------

However, now if I leave the "Use SQLITE3-Database instead of DMRIDs.dat" function enabled, the dashboard will crash and I get the error as shown in the attached image.

Of course, I entered the path of the file that is downloaded since the launch of dbupdate.sh under "Path to DMR-ID-Database-File (including filename)"(/Var/www/html/database/dmrid.dat)
I'm losing hope ...

If you have an idea......

Tnx again
‘73 de Adam, IK4NZD
