### ISSUE TITLE
YSF NOT LINKED

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#192]
I installed YSFGATEWAY on my system yesterday, and although I have declared all the paths for the .INI and LOG files, in the dashboard I always see YSF NOT LINKED even if they are correctly online and I receive traffic. 
What could be the problem ? 
Thanks

Adam

This is my log:
I: 2019-12-08 08:45:48.462 Loaded 547 YSF reflectors
I: 2019-12-08 08:45:48.462 Loaded YSF parrot
M: 2019-12-08 08:45:48.495 Starting the APRS Writer thread
M: 2019-12-08 08:45:48.495 Automatic (re-)connection to 82044 - "IT YSFROOM-ITALY"
M: 2019-12-08 08:45:48.495 Starting YSFGateway-20190131
M: 2019-12-08 08:45:48.521 Linked to IT YSFROOM-ITALY
M: 2019-12-08 08:45:48.599 Received login banner : # aprsc 2.1.4-g408ed49

M: 2019-12-08 08:45:48.634 Response from APRS server: # logresp IR4UAV-R unverified, server T2DENMARK

M: 2019-12-08 08:45:48.635 Connected to the APRS server
M: 2019-12-08 08:45:48.863 Link successful to MMDVM

![Immaginedash](https://user-images.githubusercontent.com/29512684/70386988-d3ac4b80-199f-11ea-8741-fd04e5f1c13e.jpg)

![Immaginedash1](https://user-images.githubusercontent.com/29512684/70386996-fe969f80-199f-11ea-8618-848ba0a80303.jpg)

**Comment by phl0** [comment]
@dg9vh Please have a look here

**Comment by ik4nzd** [comment]
why??

**Comment by dg9vh** [comment]
Can you post your YSFGateway.ini to take a look where your logfile is really placed?

**Comment by dg9vh** [comment]
And: what happens, if you connect manually to a reflector via DTMF or Wires-X functionallity? Maybe there is a problem with following:
M: 2019-12-08 08:45:48.495 Automatic (re-)connection to 82044 - "IT YSFROOM-ITALY"

**Comment by ik4nzd** [comment]
This is my .INI file for YSFGATEWAY.


[General]

Callsign=IR4UAV
Suffix=RPT
# Suffix=ND
Id=222456
RptAddress=127.0.0.1
RptPort=3200
LocalAddress=127.0.0.1
LocalPort=4200
WiresXMakeUpper=1
WiresXCommandPassthrough=1
Daemon=0

[Info]
RXFrequency=431987500
TXFrequency=430387500
Power=10
Latitude=44.809364
Longitude=9.9898333
Height=15
Name=Salsomaggiore Terme
Description=Multi-Mode Repeater

[Log]
# Logging levels, 0=No logging
DisplayLevel=1
FileLevel=2
FilePath=/var/log/YSFGateway
FileRoot=YSFGateway

[aprs.fi]
Enable=1
# Server=noam.aprs2.net
Server=euro.aprs2.net
Port=14580
Password=18337
Description=RPT DMR/C4FM
Suffix=Y

[Network]
Startup=IT YSFROOM-ITALY
# Startup=Alabama-Link
InactivityTimeout=10
Revert=1
Debug=0

[YSF Network]
Enable=1
Port=42000
Hosts=/etc/YSFGateway/YSFHosts.txt
ReloadTime=60
ParrotAddress=127.0.0.1
ParrotPort=42012
#YSF2DMRAddress=127.0.0.1
#YSF2DMRPort=42013
#YSF2NXDNAddress=127.0.0.1
#YSF2NXDNPort=42014
#YSF2P25Address=127.0.0.1
#YSF2P25Port=42015

[FCS Network]
Enable=0
Rooms=./FCSRooms.txt
Port=42001

[Mobile GPS]
Enable=0
Address=127.0.0.1
Port=7834

**Comment by ik4nzd** [comment]
I'm sorry, I don't know. I currently have no C4FM radio, but I have to wait for users to use it

**Comment by ik4nzd** [comment]
If the room is called by a user via radio, then on the dashboard it appears regularly (see image). 
![Immagine](https://user-images.githubusercontent.com/29512684/70456079-bcf41a80-1aad-11ea-9290-973278299cdc.jpg)
But now I restarted without starting room, and in the dashboard is still present the previous room.....
And in the log after the reboot is specified that there are NOT starting rooms.
I: 2019-12-09 16:46:50.115 Loaded YSF parrot
**_M: 2019-12-09 16:46:50.131 No connection startup_**
M: 2019-12-09 16:46:50.131 Starting the APRS Writer thread

**Comment by dg9vh** [comment]
ok. Then this is a minor bug, I would keep it in mind but actually there is a higher priority on other bugs :-)

**Comment by ik4nzd** [comment]
Okay, Kim. The important thing is to understand how it works.

But..... are you already aware of the problem that the switch between ROOM from the dashboard does not work?

Thank you
Hello, Adam.

**Comment by dg9vh** [comment]
This could be a problem with your configuration of /etc/sudoers maybe.. please check the corresponding howto-file in the files.

**Comment by ik4nzd** [comment]
My sudoers it's normally, i think…

#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

%www-data ALL=NOPASSWD: /sbin/halt, /sbin/reboot, /bin/systemctl

**Comment by dg9vh** [comment]
you need to add  /bin/sed into the list...

**Comment by ik4nzd** [comment]
added /bin/sed, but don't work....

**Comment by ik4nzd** [comment]
I added /bin/sed but it doesn't work.
The following message appears: 
**_Switching YSFReflector to GB-XLX925-C
Restarting in new selected YSFReflector in progress_** 
The YSFGateway service is restarted, but the system does not go on any ROOM

**Comment by dg9vh** [comment]
Please post the content of your /etc/sudoers...

**Comment by ik4nzd** [comment]
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root    ALL=(ALL:ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

%www-data ALL=NOPASSWD: /sbin/halt, /sbin/reboot, /bin/systemctl, /bin/sed

**Comment by dg9vh** [comment]
Does this still persist?
