### ISSUE TITLE
Missing Last Heard and Local Transmissions Callsigns

### ISSUE THREAD

**Issue by rastarasta** [dg9vh/MMDVMHost-Dashboard#195]
Using Dashboard v 20191209-1 on Pi running Ubuntu 15.1 with PHP 5.6.  

Dashboard works great, except under Last Heard and Local Transmissions, nothing is shown (except "No data available in table"), even though there has been recent activity, both local and via DMR TGs and DStar linked reflectors.   

I have checked ownership and permissions, and the web user, www-data, is either owner or group for all the web folders, from the web root and below, plus /tmp, and www-data has read in all cases, and write in most cases.  

I notice right now under Last Heard it shows for Cached there at 6/xxxxx callsigns,  In /tmp there is the file Callsign_Name.txt with 6 lines.   This matches what I have noticed monitoring this repeater.  They just don't show up on the Dashboard.

I have looked at the MMDVM logs and all callsigns with activity on the repeater have been logged there.  

So the source data is good, I think the permissions are good, and I have not been able to find what I did wrong that prevents the LH and Local TX callsigns to be missing on the Dashboard.

Any ideas will be much appreciated.

**Comment by SA7BNT** [comment]
Hey, did you set the DisplayLevel=2 FileLevel=2 inside MMDVM.ini?? And file path is the same as in the DB config?

**Comment by rastarasta** [comment]
Thanks for the suggestion. We have been running with DisplayLevel=1 and FileLevel=1

I set the Dashboard /config/config.php's MMDVMLOGPATH to where MMDVMHost writes the logs. The logs are being created and I can see them using an FTP client. They contain all callsign activity, both RF and network.

My understanding for Logging levels:

0 = No logging
1 = Debug
2 = Message
and File levels:

0 = No logging file
1 = Log to file

**Comment by dg9vh** [comment]
Hi, set FileLevel=2 and it would work as expected.

**Comment by rastarasta** [comment]
Thanks for the guidance.  I have set FileLevel=2 and tried DisplayLevel=2 and DisplayLevel=1.   Either way, the "Currently TXing" shows calls during transmit, but I continue to get "No data available in table" in the Last Heard and Today's Local Transmissions sections.  

I followed  the Linux step-By-Step instructions for file/folder ownership and permissions.  I have put in traces that show the callsigns are being logged and the scripts can read the MMDVM logs.  

But I am sure it is a local installation problem.  I've installed MMDVMHost-Dashboard version 20191201-1 onto a Pi running Ubuntu 15.1 with PHP 5.6.11.  MMDVMHost is old -- version 20170303.

I am thinking the older version of PHP may be the problem.  Or the old version of MMDVMHost.

Again, thanks for the help.

**Comment by SA7BNT** [comment]
Hallo @rastarasta,

please try to set permissions so you and the webserver have full access to the files one more time.
Maybe that will resolve the issue.

**Comment by rastarasta** [comment]
Found the problem.  We were not running the correct version of the Dashboard for the MMDVMHost version.  The latest version of Dashboard has changes to accomodate how the latest version of MMDVMHost formats its logfile.  

We plan to replace the entire gateway with a new Pi with latest MMDVMHost and Dashboard.  Until then, the Dashboard is working again.  I just commented out the latest code that extracts the log line info into variables, and un-commented the previous line of code that worked with the previous MMDVMHost logs.  Last Heard is now working for our site.

Thanks for looking into this.

**Comment by tfc001** [comment]
rastarasta  … I am trying to use this dashboard with DVSwitch and having same problem. Perhaps I have an MMDVM version problem. What lines … and where … did you enable/disable to make the dashboard work??

tnx ... Tom VE3NY

**Comment by SA7BNT** [comment]
> rastarasta  … I am trying to use this dashboard with DVSwitch and having same problem. Perhaps I have an MMDVM version problem. What lines … and where … did you enable/disable to make the dashboard work??
> tnx ... Tom VE3NY

The Dashboard will run if it can read the MMDVMHost log file. After MMDVMHost has been updated recently, the log file format has changed. Please check that your MMDVMHost log file is set correct in MMDVM-Dashboard config or try to update to the latest version. 


73


Tim de SA7BNT
