### ISSUE TITLE
Process Zombie ( Send SMS )

### ISSUE THREAD

**Issue by YV5OF** [dg9vh/MMDVMHost-Dashboard#20]
Hi Kim,

Today testing sending SMS, I note that returned appear the problem had been corrected the zombie process.

73!
YV5OF

![captura de pantalla 2016-06-16 a las 4 15 54 p m](https://cloud.githubusercontent.com/assets/19210807/16131794/23a735f6-33de-11e6-888b-03559e08adfb.png)

**Comment by dg9vh** [comment]
Can you explain the problem? The line "sending or receiving SMS" was intended to describe, that this transmission was one that was transmitting or receiving a SMS... 

Is it missunderstandable? Do we need better wording here? Or what exactly is not ok?

**Comment by YV5OF** [comment]
Ok, sorry.

I did test to send 1 SMS, the process within the MMDVMHost log ends, but in the dashboard are as bursts of connections SMS sending process.

And they are there, although fails or send SMS.

**Comment by dg9vh** [comment]
@YV5OF would check, what I can do here next week when back home from vacation.

**Comment by dg9vh** [comment]
Are this zombies still persistent? Don't see them for a long time... if, reopen this.
