### ISSUE TITLE
TX-Time

### ISSUE THREAD

**Issue by yo6nam** [dg9vh/MMDVMHost-Dashboard#203]
On the dashboard under the "Currently TXing" the TX-Time starts from -10800s and counts backwards. Is this normal?

**Comment by dg9vh** [comment]
No, are you using current version of MMDVMHost and current version of Dashboard? What timezone did you configure on your system and what timezone is selected on the dashboard?

**Comment by dg9vh** [comment]
Please take also a look at the error.log of your webserver to see, if there are some issues.

**Comment by yo6nam** [comment]
Kim, you are correct. I was using a modified MMDVMHost version and I think the change in Log.cpp from "gmtime" to "localtime" affects the log file read by the dashboard.
Thank you and sorry for the unnecessary troubles.

**Comment by dg9vh** [comment]
No problem... if you are doing this, you should also modify the corresponding files within the dashboard :-) you would find the code within https://github.com/dg9vh/MMDVMHost-Dashboard/blob/master/txinfo.php and there you should put some offset onto the calculation... then you have the right numbers again :-)
73 de Kim
