### ISSUE TITLE
Installation problem with Raspian Buster

### ISSUE THREAD

**Issue by ik4nzd** [dg9vh/MMDVMHost-Dashboard#204]
Hi everyone.
I am creating a new plant with the latest Raspian Buster Lite.
I am following the instructions of the linux-step-by-step.md but I find problems when I install SQL.

If I use

**sudo apt-get install php5-common php5-cgi php5**

i get this error

_pi @ raspberrypi: ~ $ sudo apt-get install sqlite3 php5-sqlite
Reading package lists ... 
Done
Building dependency tree
Reading state information ... 
Done
Package php5-sqlite is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'php5-sqlite' has no installation candidate_

while if I use

**sudo apt-get install sqlite3 php7.0-sqlite**

i get this error

_pi @ raspberrypi: ~ $ sudo apt-get install sqlite3 php7.0-sqlite
Reading package lists ... 
Done
Building dependency tree
Reading state information ... 
Done
E: Unable to locate package php7.0-sqlite
E: Couldn't find any package by glob 'php7.0-sqlite'
E: Couldn't find any package by regex 'php7.0-sqlite'_

can you please help me install the package?
Thanks

'73 de Adam, IK4NZD

**Comment by dg9vh** [comment]
Hi, it is recommended to use  php7.3 and php7.3-sqlite3
Actually I have no time to actualize the install-howto... so if someone would find some time - just grab it :-)
