### ISSUE TITLE
MMDVMHost-Dashboard on Pi-Star

### ISSUE THREAD

**Issue by JeffHochberg** [dg9vh/MMDVMHost-Dashboard#208]
Hello,

Is there a way to configure MMDVMHost-Dashboard to run on top of Pi-Star? I followed the step-by-step configuration and have most of it working, but there are a few areas on the dashboard where it's unable to display some of the data. I tried to reverse engineer the Pi-Star configuration to locate the equivalent files for MMDVMHost and DMR Gateway, but I must have some of the paths/filenames/prefixes incorrect.

**Comment by dg9vh** [comment]
I don't see any sense in running my dashboard on top of pi-star because pi-star has it's own dashboard.

If you want to use pi-star, please contact corresponding forum of pi-star.
