### ISSUE TITLE
MMDVMHost SimpleDMR version

### ISSUE THREAD

**Issue by picchiosat** [dg9vh/MMDVMHost-Dashboard#213]
Hi Kim,
G4KLX has opened a new branch for MMDVMHost called SimpleDMR.
In this branch MMDVMHost no longer connects in a "traditional" way and the use of DMRGateway is mandatory for connection with the various networks.
This means that the DMR-Master always remains offline on the dashboard because there is no real MMDVM connection.
Could you make a "SimpleDMR" version of the dashboard where, as for YSFGateway, see if the process is active?

Roby IV3JDV

**Comment by dg9vh** [comment]
Hi, I am sorry, but actually I have no spare time for such big things. My job, family and health actually takes time with higher priorities.

Because this is open source and free, everyone who is able to do it will be allowed to take the code and build something new from it.

**Comment by dg9vh** [comment]
To come back to this issue: I am actually using the recommended setup (compiled yesterday) and I have no problem with offline-Master...

I configured the gateway as DMRMaster and so it shows following on my actual Dashboard-Version:

![image](https://user-images.githubusercontent.com/13950650/93775338-91988180-fc22-11ea-9f9c-91f7f0a0ba8a.png)

Did I something wrong in configuration? On my side it's working ufb :-)

So please get me more info for example your MMDVM.ini to see, how you had configured it.

73 de Kim

**Comment by picchiosat** [comment]
Thanks Kim for the answer.
With the MASTER branch everything works fine and there are no problems.
Jonathan opened another branch, SimpleDMR, where MMDVMHost no longer connects to DMRGateway in the "traditional" way and does not make an MMDVM connection. In the logs, therefore, there are no longer the connection strings and on the dashboard it always remains offline.
Since it's a Beta branch you don't need to waste time making changes.
When the version is "mature" then we'll think about it.

Best 73 Roby

**Comment by dg9vh** [comment]
Ok, will start developing in this way, when g4klx moves this into the master branch...
