### ISSUE TITLE
RF stations TX time

### ISSUE THREAD

**Issue by m1aeg** [dg9vh/MMDVMHost-Dashboard#219]
Hi
Using latest version of MMDVMHost, (01/01/2021) Tx time for RF stations keeps counting even when station has stopped transmitting. Network traffic TX time is OK.
If I manually edit the MMDVMHost log file to include the field "0% packet loss" the TX timer stops counting.
Is there a change in latest MMDVMHost that changes the log file and affects the dashboard code?
See log lines below. RF log entry does not include packet loss field and causes issue. 

M: 2021-03-20 14:09:39.249 YSF, received RF end of transmission from M1AEG      to DG-ID 10, 2.4 seconds, BER: 0.4%
M: 2021-03-20 14:19:39.758 YSF, received network data from M1AEG      to DG-ID 12 at GB3HB     
M: 2021-03-20 14:19:46.972 YSF, network watchdog has expired, 5.9 seconds, 0% packet loss, BER: 0.0%
M: 2021-03-20 14:50:18.876 YSF, received network data from G0JYQ      to DG-ID 11 at GB3HB     
M: 2021-03-20 14:50:21.079 YSF, received network end of transmission from G0JYQ      to DG-ID 11, 2.4 seconds, 0% packet loss, BER: 0.0%

**Comment by dg9vh** [comment]
Must check this... is this log-excerpt with actualversion of MMDVMHost?

**Comment by dg9vh** [comment]
Actually I have a Version MMDVMHost by G4KLX Version: 20210101 (compiled 21 Feb 2021, GitID #b64359a) running at my side that produces the following log line in direct compare to yours below:
```
M: 2021-03-20 19:36:33.911 YSF, received RF end of transmission from DG9VH      to DG-ID 0, 5.9 seconds, BER: 0.3%, RSSI: -47/-47/-47 dBm
M: 2021-03-20 14:09:39.249 YSF, received RF end of transmission from M1AEG to DG-ID 10, 2.4 seconds, BER: 0.4%
```
You can see, that there is no real difference - I am actually upgrading my MMDMVHost and will retest with actual situation.

**Comment by dg9vh** [comment]
Sorry, I can't reproduce this issue with actual MMDVMHost and actual Dashboard-Version.

**Comment by dg9vh** [comment]
Also disabled the RSSI-reporting on my hotspot it does not issue this... So this must be another problem...

Are you running actual Dashboard-version?

**Comment by m1aeg** [comment]
[MMDVMHost-2021-03-16.log](https://github.com/dg9vh/MMDVMHost-Dashboard/files/6176560/MMDVMHost-2021-03-16.log)

**Comment by m1aeg** [comment]
Hi Kim
Thank you for taking time to diagnose this. I will try to send a log file where the problem occurs.
The live dashboard is at http://ysf.gb3hb.co.uk 
You will maybe see the problem at some point...

**Comment by dg9vh** [comment]
It seems to me that you have debug and wrong file level enabled

**Comment by m1aeg** [comment]
Thanks Kim

I have FileLevel=1, DisplayLevel=0 and Debug=0 in MMDVMHost.ini but I agree there seems to be debug messages in logfile.

I will recompile MMDVMHost to ensure it’s not an error in that.

**Comment by m1aeg** [comment]
Kim

 

The problem is only present when only a single mode is enabled in MMDVMHost.

My gateway is purely YSF so D-Star & DMR are disabled. If I enable D-Dstar then the problem is not present. I hope this helps with diagnosis.

 

Thanks again, your help is much appreciated.

**Comment by dg9vh** [comment]
Please try with FileLevel = 2.

**Comment by m1aeg** [comment]
I have tried FileLevel=2 and get the same problem.
As per my last email, if only YSF mode is enabled in MMDVM.ini then the problem exists.
As soon as D-Star is enabled in MMDVM.ini the problem does NOT exist and all works fine.
Are you able to replicate the problem at your end ?
Many thanks

**Comment by dg9vh** [comment]
Sorry, I can't replicate this... I am running here a dual-hat in YSF single-mode, too without any problems like this...

I also did not reproduce the problem with your logfile... I downloaded it and copied it on my system with correct name... it was parsed (very slow because of size) but there was no issue.
