### ISSUE TITLE
File setup.php

### ISSUE THREAD

**Issue by ayasystems** [dg9vh/MMDVMHost-Dashboard#23]
Why the fields of section "YSFGateway-Configuration" and "ircddbgateway-Configuration" are flaged as required?

I don't use these parts so what value must be set? "NULL" ??

Regards!

**Comment by dg9vh** [comment]
Yes, you are right...  you can do following:

do not enable the YSFGateway-sections by unselecting the option "Enable YSFGateway" and write something into the corresponding fields... something means everything but NULL.

The option-switcher enables/disables the complete module... but actually it is not enabling/disabling the plausibility-check in the form... would look, what I can do there.

**Comment by m1geo** [comment]
Seconded for this problem...

**Comment by dg9vh** [comment]
solved with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/0f51be1ce732444536d925ce1d417db245620348
