### ISSUE TITLE
Make reload of page switchable by button

### ISSUE THREAD

**Issue by dg9vh** [dg9vh/MMDVMHost-Dashboard#25]
Version a) via Javascript?
Version b) via URL-Parameter to disable refresh in head-section?

**Comment by pjao** [comment]
I think you should go with version b).

Version a) could be easier, but will fail if JavaScript is disable on browser.

**Comment by dg9vh** [comment]
done with link in footer. closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/20d216e68b65c1fb9eace03dae30c0328565ba35
