### ISSUE TITLE
Add name-lookup

### ISSUE THREAD

**Issue by dg9vh** [dg9vh/MMDVMHost-Dashboard#26]
Adding name lookup onto the callsign-lookup via local DMRIds.dat-lookup.
- [ ] make test-implementation of lookup-routine for time-mesurment
- [ ] if exec-time is ok, make it switchable via config.php/setup.php

**Comment by pjao** [comment]
MMDVMHost  doesn't do it already?

Disable on MMDVMHost  and enable it on MMDVMHost-Dashboard?

**Comment by dg9vh** [comment]
No, MMDVMHost only does Callsign-lookup, without name...

Without modifying MMDVMHost-source (no-go) no name is delivered.

**Comment by pjao** [comment]
Sorry! Bad interpretation! 
Could be nice, and it should not give high load. Shell script is very fast: 
cat /etc/DMRIds.dat | grep CT2JAY | cut -c16-

**Comment by dg9vh** [comment]
Maybe a good idea to put the DMRIds.dat onto a ramdisk... I put my logs allready on ramdisk to protect sd-card from fail by to many write-access.

**Comment by pjao** [comment]
DMRIds.dat isn't read-only? Updated only by script, once a day in the best practical cases...

**Comment by dg9vh** [comment]
DMRIds.dat is read-only during runtime, but I think ramdisk-access would be much faster than sd-card... just in view of performance :-)

**Comment by dg9vh** [comment]
closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/097f18881ada23d2eca9a6dcbc37f6b74e585236

**Comment by dg9vh** [comment]
bugfixed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/92fc6116912755b2bb53a1a388a4a859efae4380
