### ISSUE TITLE
Resolve Name

### ISSUE THREAD

**Issue by YV5OF** [dg9vh/MMDVMHost-Dashboard#28]
Hi Kim,

I'm testing name resolution, I tried to place the file DMRIds.dat:

/ Tmp /
/etc/
and the path where I have the MMDVMHost (/ home / pi / Downloads / MMDVMHost /)

Everything works correctly but does not show the name,

Perform a completely clean installation of MMDVMHost-Dashboard, but I can not display the names.

My Dashboard : http://mmdvm.ddns.net:8081/

73!
YV5OF - Severino

**Comment by pjao** [comment]
Do you enable it with setup.php?

You have two more options: Enable extended lookup (show names) and Path to DMR-ID-Database-File

Paulo - CT2JAY

**Comment by YV5OF** [comment]
Thx Paulo,

All is Yes. This my config.php : ( And using NGINX )

date_default_timezone_set('UTC');
define("MMDVMLOGPATH", "/mnt/ramdisk/");
define("MMDVMLOGPREFIX", "MMDVM");
define("MMDVMINIPATH", "/home/pi/Downloads/MMDVMHost/");
define("MMDVMINIFILENAME", "MMDVM.ini");
define("MMDVMHOSTPATH", "/home/pi/Downloads/MMDVMHost/");
define("ENABLEXTDLOOKUP", "on");
define("DMRIDDATPATH", "/etc/");
define("YSFGATEWAYLOGPATH", "/mnt/ramdisk/");
define("YSFGATEWAYLOGPREFIX", "YSFGateway");
define("YSFGATEWAYINIPATH", "/etc/");
define("YSFGATEWAYINIFILENAME", "YSFGateway.ini");
define("LINKLOGPATH", "/var/log/opendv/");
define("IRCDDBGATEWAY", "ircddbgateway");
define("REFRESHAFTER", "30");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("ENABLEMANAGEMENT", "on");
define("REBOOTMMDVM", "sudo systemctl restart mmdvmhost");
define("REBOOTSYS", "sudo reboot");
define("HALTSYS", "sudo halt");
?>

**Comment by dg9vh** [comment]
Did you call setup.php and put in the whole filepath? /home/piDMRIds.dat for example?

**Comment by dg9vh** [comment]
You have to put the filename also into the config. So /etc/mmdvm/DMRIDds.dat is needed

**Comment by YV5OF** [comment]
Many Thanks Kim, had just placed the route + file name started to work.

73!
