### ISSUE TITLE
dashboard stopped working again 

### ISSUE THREAD

**Issue by scotta1980** [dg9vh/MMDVMHost-Dashboard#30]
this is what i am getting from the error.log

2016-07-16 16:57:00: (log.c.164) server started 
2016-07-16 16:57:33: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/include/functions.php on line 220
2016-07-16 16:59:47: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/include/functions.php on line 218

**Comment by dg9vh** [comment]
can you post your config.php, please?

**Comment by scotta1980** [comment]
date_default_timezone_set('UTC');
define("MMDVMLOGPATH", "/home/pi");
define("MMDVMLOGPREFIX", "MMDVM");
define("MMDVMINIPATH", "/home/pi");
define("MMDVMINIFILENAME", "MMDVM.ini");
define("MMDVMHOSTPATH", "/home/pi/Applications/MMDVMHost");
define("ENABLEXTDLOOKUP", "on");
define("DMRIDDATPATH", "/home/pi/DMRIds.dat");
define("YSFGATEWAYLOGPATH", "0");
define("YSFGATEWAYLOGPREFIX", "0");
define("YSFGATEWAYINIPATH", "0");
define("YSFGATEWAYINIFILENAME", "0");
define("LINKLOGPATH", "/var/log");
define("IRCDDBGATEWAY", "ircddbgateway");
define("REFRESHAFTER", "30");
define("SHOWPROGRESSBARS", "on");
define("TEMPERATUREALERT", "on");
define("TEMPERATUREHIGHLEVEL", "60");
define("REBOOTMMDVM", "");
define("REBOOTSYS", "");
define("HALTSYS", "");

**Comment by dg9vh** [comment]
The config above means, your MMDVM-logfile is in /home/pi? Also your MMDVM.ini?
Can you post your MMDVM.ini, please? 

How do you start MMDVMHost? With which parameter?

**Comment by scotta1980** [comment]
MMDVMHost auto starts when system boots up 

[General]
Callsign=MM3LSO
Timeout=180
Duplex=0

# ModeHang=10

RFModeHang=3
NetModeHang=10
Display=None
Daemon=0

[Info]
RXFrequency=431800000
TXFrequency=431800000
Power=1
Latitude=0.0
Longitude=0.0
Height=0
Location=Eyemouth Scottish Borders
Description=Multi-Mode Repeater
URL=www.google.co.uk

[Log]

# Logging levels, 0=No logging

DisplayLevel=1
FileLevel=1
FilePath=/home/pi
FileRoot=MMDVM

[CW Id]
Enable=1
Time=10

[Modem]
Port=/dev/ttyAMA0

# Port=\.\COM3

TXInvert=1
RXInvert=0
PTTInvert=0
TXDelay=100
DMRDelay=0
RXLevel=50
TXLevel=50
DStarLevel=0
DMRLevel1=0
DMRLevel3=0
YSFLevel1=0
YSFLevel3=0
DMRThreshold=0
YSFThreshold=0
OscOffset=-100
Debug=0

[D-Star]
Enable=1
Module=B
SelfOnly=0

[DMR]
Enable=1
Beacons=1
Id=2354008
ColorCode=1
SelfOnly=0

# Prefixes=234,235

LookupFile=DMRIds.dat
CallHang=3
TXHang=4
#Blacklist=
#DstIdBlackListSlot1=
#DstIdBlackListSlot2=
#DstIdWhiteListSlot1=
#DstIdWhiteListSlot2=

[System Fusion]
Enable=0

[D-Star Network]
Enable=1
GatewayAddress=127.0.0.1
GatewayPort=20010
LocalPort=20011
Debug=0

[DMR Network]
Enable=1
Address=91.121.101.163 
Port=62031

# Local=3350

Password=passw1rd
Slot1=1
Slot2=1
Debug=0

[System Fusion Network]
Enable=0
LocalAddress=127.0.0.1
LocalPort=3200
GwyAddress=c4fm.duckdns.org
GwyPort=4200
Debug=0

[TFT Serial]
Port=/dev/ttyAMA0
Brightness=50

[HD44780]
Rows=2
Columns=16

# For basic HD44780 displays (4-bit connection)

# rs, strb, d0, d1, d2, d3

Pins=11,10,0,1,2,3

# Device address for I2C

I2CAddress=0x20

# PWM backlight

PWM=0
PWMPin=21
PWMBright=100
PWMDim=16

DisplayClock=1
UTC=0

[Nextion]
Port=/dev/ttyAMA0
Brightness=50
DisplayClock=1
UTC=0
IdleBrightness=20

[OLED]
Type=3
Brightness=0
Invert=0

**Comment by dg9vh** [comment]
Please try
FileLevel=2
in Log-Section.

**Comment by scotta1980** [comment]
changed FileLevel=2 but still not showing up the error log keeps pointing towards functions.php

**Comment by dg9vh** [comment]
can you give me output of 
ls -lah /home/pi/MMDVM*
?
Want to see, how large the logfiles are - if there is a problem within them...
You can also please give me a tail -n 20 /home/pi/MMDVM-2016-07-16.log

**Comment by scotta1980** [comment]
/home/pi/MMDVMHost-Dashboard:
total 60K
drwxr-xr-x  6 pi pi 4.0K Jul  3 22:27 .
drwxr-xr-x 27 pi pi 4.0K Jul 16 21:27 ..
drwxr-xr-x  8 pi pi 4.0K Jul  3 22:27 .git
-rw-r--r--  1 pi pi   27 Jul  3 22:27 .gitignore
drwxr-xr-x  2 pi pi 4.0K Jul  3 22:27 include
-rw-r--r--  1 pi pi 3.8K Jul  3 22:27 index.php
-rw-r--r--  1 pi pi 6.5K Jul  3 22:27 LICENSE
-rw-r--r--  1 pi pi 2.2K Jul  3 22:27 linux-step-by-step.md
-rw-r--r--  1 pi pi 2.1K Jul  3 22:27 README.md
drwxr-xr-x  2 pi pi 4.0K Jul  3 22:27 scripts
-rw-r--r--  1 pi pi 9.3K Jul  3 22:27 setup.php
drwxr-xr-x  2 pi pi 4.0K Jul  3 22:27 sounds
pi@raspberrypi:~$

**Comment by scotta1980** [comment]
pi@raspberrypi:~$ tail -n 20 /home/pi/MMDVM-2016-07-16.log
I: 2016-07-16 21:28:03.913 CW Id Parameters
I: 2016-07-16 21:28:03.913     Time: 10 mins
I: 2016-07-16 21:28:03.913 D-Star Parameters
I: 2016-07-16 21:28:03.913     Module: B
I: 2016-07-16 21:28:03.913     Self Only: no
I: 2016-07-16 21:28:03.914 DMR Parameters
I: 2016-07-16 21:28:03.914     Id: 2354008
I: 2016-07-16 21:28:03.914     Color Code: 1
I: 2016-07-16 21:28:03.914     Self Only: no
I: 2016-07-16 21:28:03.914     Prefixes: 0
I: 2016-07-16 21:28:03.914     Lookup File: DMRIds.dat
I: 2016-07-16 21:28:03.914     Call Hang: 3s
I: 2016-07-16 21:28:03.914     TX Hang: 3s
I: 2016-07-16 21:28:04.130 Loaded 38788 DMR Ids to the callsign lookup table
M: 2016-07-16 21:28:04.130 MMDVMHost-20160624 is running
M: 2016-07-16 21:28:14.006 Logged into the master successfully
M: 2016-07-16 21:29:22.821 DMR Slot 2, received network voice header from MI0SAM to TG 9
M: 2016-07-16 21:29:30.721 DMR Slot 2, received network end of voice transmission, 7.5 seconds, 8% packet loss, BER: 0.0%
M: 2016-07-16 21:29:56.656 DMR Slot 2, received network voice header from MI0SAM to TG 9
M: 2016-07-16 21:30:04.525 DMR Slot 2, received network end of voice transmission, 7.5 seconds, 6% packet loss, BER: 0.0%

**Comment by dg9vh** [comment]
ok, nw please:

   ls -lah /home/pi/MMDVM-2016-07-16.log

**Comment by scotta1980** [comment]
-rw-r--r-- 1 root root 44M Jul 16 21:35 /home/pi/MMDVM-2016-07-16.log

**Comment by dg9vh** [comment]
ok... please shutdown MMDVMHost
mv /home/pi/MMDVM-2016-07-16.log /home/pi/MMDVM-2016-07-16.log.old
and
restart MMDVMHost again. If ready, make a transmission and reload Dashboard... I think 44Megabytes of logfile would be the problem... it would be far to big, I think...

**Comment by scotta1980** [comment]
thanks kim that worked dashboard is now showing how can wee stop this from happening again is the log file getting to large

**Comment by dg9vh** [comment]
You did your part by setting the loglevel to 2 - so less "rubbish" is getting into the log. Level 1 is very "loud" in output... nw. your logfile would be much more smaller than that... even if running 24/7.

mine does rarely explode to more than 10 MB... normally it is about 2-3 MB... So 44 was hell :-)

OK so 73 and we hope the best...
