### ISSUE TITLE
localtx.php no longer limits 'Local Transmissions" list (was 10 entries)

### ISSUE THREAD

**Issue by ve1aic** [dg9vh/MMDVMHost-Dashboard#33]
A couple of days ago I updated my Dashboard to:
MMDVMHost-Dashboard V 20160721-1

 I found that the "Local Transmissions" was no longer paging or restricted to last-10 entries. My dashboard was filled with pages of data as I had a busy morning on the repeater.
Number of entries displayed was 218.

A previous version of localtx.php has this local list limited to 10 entries.
Perhaps there was supposed to be a defined limit but can't find anything new in config.php.
(Just the 'Last Heard' limit).
73, Ron
VE1AIC

p.s. I resorted the previous version of localtx.php that has the counter==10 for now.

**Comment by dg9vh** [comment]
Hi Ron,

I think, it could be an issue with loading the javascripts from the cdn-servers for the datatables (that's the type of html-table combined with javascript for sorting/searching I use in the dashboard for the lh-lists and so on)... I will try next days what happens, if I put the javascripts local on the raspberry pi where the dashboard's running.

I also can see the problem but only for a few seconds here... first I have a very long list then after 3 seconds the datatable is created. I think, it takes this 3 seconds to get the javascript from the forreign server.

Normally I don't have this problem with lists that are very long (for example after 23 hours running on a day...).

If the issue still exists on the new way (I will test it next days), I maybe go following way:

I limit the lists to 40 entries and give a link to a separate page to load only one special list (for example last heard or local transmissions) with all entries... so if someone wants to search whithin the complete list, he can fetch all entries "on demand" in this extra pages.

But first I try to load the scripts from local server and test it out.

**Comment by ve1aic** [comment]
You're right about the javascript. That section "Show 10 entries        Search:"  is loaded externally.
Since I run a NoScript plug-in it can be blocked unless explicitly allowed per web site.
Example, I go to your dashboard and I see NO paging but if I allow the javascript for all parts then it works properly. I was confused because your previous version used a "counter++" to limit entries.
73, Ron

**Comment by dg9vh** [comment]
After testing for the last two weeks I can say, it makes no differences for the loading-time of the dashboard, if the scripts and stylesheets are loaded from the internet or from the location of the dashboard. Differences would be ms but changing by random which solution is faster... so I would say: no difference.

**Comment by dg9vh** [comment]
closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/244539f0ee4ebd1e0837f1d3ca381bc657184cf1 - additional hint to make javascript enabled.
