### ISSUE TITLE
monitoring gpio status

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#34]
Hi, I had added to my mmdvm repeater a battery backup and I will be happy if it is possible monitoring the power supply status over the dashboard. 
I think to use the gpio status applying a voltage level. is it possible visualize the gpio status on the dashboard?  
thank you so much 
73 de IW9GRL

**Comment by dg9vh** [comment]
I don't know. Did not work with GPIO-ports ever... I think, if you have a command-line-tool, that could generate a simple text-file containing the voltage value, this could easily be shown on the dashboard.

**Comment by iw9grl** [comment]
Hi 
thank you for your prompt answer. 
is not important to visualize the voltage level, but a flag is enough, battery mode on or off. 
I have to verify if in some file the gpio status is written. 
I'm verifying.....  tnx for now
73

**Comment by iw9grl** [comment]
using the following php code:

<?php $pinStatus = trim(shell_exec("gpio -g read 18"));
//returns 0 = low; 1 = high
echo $state[$pinStatus];?>

is possible to know if the level is 0 or 1,is it enough to implement in the code? 
tnx

**Comment by dg9vh** [comment]
I think, this would be enough... what package has to be installed on the raspi to get the gpio-command? And: What conditions control pin18?

**Comment by dg9vh** [comment]
I think you use the wiring-pi-package, right?

**Comment by dg9vh** [comment]
So next question is: How do you signalize that you are on battery? Do you put the pin on high-level via transistor or something like that? Or other: How is the mapping of 0 and 1: 0 = online, 1 = on battery or vice versa?

**Comment by dg9vh** [comment]
done with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/9848126256b2ef12bafe5ae305885eb274421429

**Comment by dg9vh** [comment]
use setup.php to configure PIN and mapping of online-state

**Comment by iw9grl** [comment]
hi kim
yes, I use wiringPi and with a diode and transistor I put 5v or gnd  to a gpio, in this case gpio 18.
I don't know how recognize it, for me is not important, we can use gnd (0v) for battery active and 5v for not active..... 
tnx

**Comment by dg9vh** [comment]
As you can see in the setup.php now, it is "free configurable" what state (1 or 0) the "online"-state represents. The other one is logically battery driven :-) So if you do a git pull now, you can call setup.php and put your values into the new config-fields and the world is turning around again :+1:

**Comment by iw9grl** [comment]
thank you so much for your appreciated support and availability.
I will test as soon as possible

73 de IW9GRL
