### ISSUE TITLE
Slow to refresh screen

### ISSUE THREAD

**Issue by g7kbr67** [dg9vh/MMDVMHost-Dashboard#36]
Hi 

Noticed that it now takes a while to reload the dashboard.  

Regards

Paul
G7KBR

**Comment by dg9vh** [comment]
@g7kbr67 Hi, this is a known issue and based on the fact, that the dashboard is loading the whole log of the MMDVMHost. To procede the log after a whole day takes some time.

Looking for some mechanism to speed this up but does not get any idea that could be proceded by all the users of the dashboard for installing...

**Comment by g7kbr67** [comment]
Hi Ok

That makes sense as I had the system on all day.  I noticed that I had a lot of callsigns but it ran out at the end of the page.  No way to have them in groups of 10 then select page two?  

Regards

**Comment by dg9vh** [comment]
well, this is another idea but also with some problems, because reading the log-file starts at the beginning of the file and reads it till the end... you can't start reading from the end. And here starts the problem,hi...

I am researching for speeding the thing a bit up but this has to be in a way, that others can set it up.

**Comment by dg9vh** [comment]
Getting a little bit more speed (< 10%) by changeing loading-process of log with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/4384ff6cdf1e182c8add946c9bb62fc553bee34d

**Comment by g7kbr67** [comment]
Hi Kim

What the best way to update with this commit?

I will give it a go.

Regards

Paul

Sent from my iPhone

On 15 Sep 2016, at 21:48, Kim - DG9VH <notifications@github.com<mailto:notifications@github.com>> wrote:

Getting a little bit more speed (< 10%) by changeing loading-process of log with 4384ff6https://github.com/dg9vh/MMDVMHost-Dashboard/commit/4384ff6cdf1e182c8add946c9bb62fc553bee34d

**Comment by dg9vh** [comment]
I would suggest a simple git pull to get at least the actual version of the dashboard. Only commiting one commit would not be prefered.

so just do a "git pull" within the local repository directory (if you got the initial installation with git clone...)

Else you could simply get the ZIP again and extract it, call setup.php to look, if there is anything new for you to configure and then save config, move setup.php out of the folder and then all is ok.

**Comment by g7kbr67** [comment]
Hi Kim

Did a Git pull and it downloaded updates see screenshot below:

[cid:image001.png@01D210E1.69018900]

Not sure if I need to run another command?

Regards

Paul

**Comment by dg9vh** [comment]
@g7kbr67 Sorry, but your screenshot is not visible to me. could you send it via email to me? dg9vh @ darc . de

73 de Kim

**Comment by dg9vh** [comment]
seems to be working with tmp-file for name resolution as expected... closed
