### ISSUE TITLE
Error 500 on all commits newer than 6e5717

### ISSUE THREAD

**Issue by m1geo** [dg9vh/MMDVMHost-Dashboard#46]
Hi Kim. 

Any commits newer than 6e5717 result in a error 500. 6e5717 (logo on page) works fine. 

I will try to find out why tomorrow (after sleeping, it's 4am now).

"git checkout 6e5717" got the dash working again. 

Will look more later. Unless someone beats me to it. 

George M1GEO.

**Comment by m1geo** [comment]
Seems re-running setup.php with the exact same values worked with the current master (5251f2).

G.

**Comment by dg9vh** [comment]
I think, it has to do with unset/not existing YSFHost.ini file. I'll fix it during the day.
Meanwhile keep sure, that your YSFGateway is on current version and you configured path and name of hostsfile in setup correctly.

Am 01.10.2016 05:27 schrieb George Smart notifications@github.com:Seems re-running setup.php with the exact same values worked with the current master (5251f2).

G.

**Comment by m1geo** [comment]
Thanks, Kim. 
As always, I'm up to date. Your effort is greatly appreciated! 
M1GEO.
On 1 Oct 2016 08:18, Kim - DG9VH notifications@github.com wrote:I think, it has to do with unset/not existing YSFHost.ini file. I'll fix it during the day.
Meanwhile keep sure, that your YSFGateway is on current version and you configured path and name of hostsfile in setup correctly.

Am 01.10.2016 05:27 schrieb George Smart notifications@github.com:Seems re-running setup.php with the exact same values worked with the current master (5251f2).

G.
