### ISSUE TITLE
YSFReflectors reported active not showing 

### ISSUE THREAD

**Issue by scotta1980** [dg9vh/MMDVMHost-Dashboard#47]
i have updated to the latest dashboard but the YSFReflectors reported active not showing 
i am running MMDVMHost-Dashboard V 20160930-3
i have the dashboard pointing to the new stile YSFHosts.txt but its not showing up

**Comment by dg9vh** [comment]
@scotta1980 Are you using the lastest version of YSFGateway and did you configure the right path and filename in setup.php?

**Comment by scotta1980** [comment]
sorry fixed now had it pointing to the old YSFHosts.txt all working now
