### ISSUE TITLE
Dashboard doesn' report wiresx reflectors active 

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#48]
Hi

with the last update of YSFGateway, the dashboard doesn't report the list of the Active wiresx reflector
there is somethings to do ?

tnx
73

**Comment by dg9vh** [comment]
Yes, you should have to upgrade to current YSFGateway-Version AND configure within setup.php the path to the YSFHosts.txt and the name of the file (mostly YSFHosts.txt).

Additionally you should read the readme.md of YSFGateway - there are infos on how to actualize the YSFHosts.txt in the new format...

**Comment by iw9grl** [comment]
thank you ....  my mistake in the name of file YSFHosts

73
