### ISSUE TITLE
Last update read log problem

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#49]
Hi

after the last pull the dashboard doesn't read the log and I don't see any in the dashboard .
The config.php is the same of the previous one .

73

**Comment by dg9vh** [comment]
@iw9grl Do you have Javascript enabled? Are there any log-messages in /var/log/<webserver>/error.log?

**Comment by iw9grl** [comment]
Hi
the last update require javascript ? How I have to enable ?
tnx

**Comment by dg9vh** [comment]
@iw9grl for enabling Javascript, you can find information on http://www.enable-javascript.com/en/

**Comment by iw9grl** [comment]
My BROWSER have javascript enabled ....

**Comment by iw9grl** [comment]
I made only git pull and copy the old config.php ........

**Comment by dg9vh** [comment]
@iw9grl ok, that's good. Now, do you have any error-messages in error.log of webserver? That would help me looking for the issue.

**Comment by iw9grl** [comment]
Sorry, no error message, I have error regarding other issue : Undefined offset:0 in var/www/html/dash/include/functions.php on line 592

**Comment by iw9grl** [comment]
there is something extra to install to work with ajax ?

**Comment by dg9vh** [comment]
@iw9grl do you have enabled name-lookup? if so, do you have configured the DMRIds.dat in config.php correctly? You have to put the complete path including filename (for example /home/pi/DMRIDs.dat) into the box...

No, there is nothing extra to work with ajax... needed included in dashboard.

**Comment by iw9grl** [comment]
It is strange, I use the same config.php used in the previous commits. I will investigate. Thanks for now

**Comment by dg9vh** [comment]
maybe cleaning browser's cache could also help :-)

**Comment by iw9grl** [comment]
I don't know, now it works, but it takes very long time to draw the last heard contacts

**Comment by dg9vh** [comment]
ok, this is a known issue... see https://github.com/dg9vh/MMDVMHost-Dashboard/issues/36

**Comment by iw9grl** [comment]
Thank you, but there is not already a solution .........

**Comment by dg9vh** [comment]
@iw9grl Yes, but work in progress... I am searching for some ideas to get things faster...
