### ISSUE TITLE
Show DVMega Firmware version

### ISSUE THREAD

**Issue by mrickey** [dg9vh/MMDVMHost-Dashboard#50]
It would be really nice if the dashboard could show the DVMega firmware version.

This is an important piece of information and is difficult to access when running without a local display.

You would not need to show this on the main dashboard, but you could have a secondary page that shows version numbers for many things...firmware, MMDVMHost, Raspian, etc.

Thanks for all your work.

Michael - AF6FB

**Comment by dg9vh** [comment]
@mrickey I'll take a look at it.

**Comment by dg9vh** [comment]
closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/39b8852f15393947b67f2178f1b1831a9d82b4c9
