### ISSUE TITLE
Showing TGname after TGnumber 

### ISSUE THREAD

**Issue by faxe2110** [dg9vh/MMDVMHost-Dashboard#52]
Is it possible to show the TG name after the TG number in the Repeater info??

ex. 
**DMR TS1 last linked to TG 262 (DL ALL)
DMR TS2 last linked to SA7BNT/Reflector 4020 (Niedersachsen-Mitte)**

Maybe a great feature
73
SA7BNT
Tim

**Comment by phl0** [comment]
That info is apparently not provided my MMDVMHost and it depends on the DMR network you are connected to. We have a similar solution in md380tools: https://github.com/travisgoodspeed/md380tools/issues/136

**Comment by dg9vh** [comment]
@phl0 getting the reflectors lists from the masterservers is one of my ideas to realize this like in md380tools :-)

Actually I got no time to do this, but I think, it would be possible...

**Comment by marrold** [comment]
I can't make any commitments, but I am willing to look into this.

**Comment by dg9vh** [comment]
Ok... I had it in mind with low priority...
