### ISSUE TITLE
Removed MMDVMLOGPREFIX from setup, fetching it from MMDVM.ini 

### ISSUE THREAD

**Issue by pjao** [dg9vh/MMDVMHost-Dashboard#56]
Hi there!

You need also to change in log.php and other places...

With the variable set on config "Viewing log /var/log/mmdvm/MMDVM-2016-10-28.log"
Without it set "Viewing log /var/log/mmdvm/MMDVMLOGPREFIX-2016-10-28.log"

Chears,
Paulo - CT2JAY

l "https://github.com/dg9vh/MMDVMHost-Dashboard/commit/b39624131c2e4c42ad10bc77548101af385213c5"

**Comment by dg9vh** [comment]
You are right. Would fix it soon as possible.

**Comment by dg9vh** [comment]
fixed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/c2c27b36f40e08a8360489f4fe8f1f4927cad9ee
