### ISSUE TITLE
Network switching Buttons

### ISSUE THREAD

**Issue by dc7jzb** [dg9vh/MMDVMHost-Dashboard#57]
Little Question,

In the Screenshot from SA7BNT i saw two Buttons to switch between DMR+ and Brandmeister.

Is this a function of the Dashboard and I have not seen it ?
Or is this "selfmade" by SA7BNT ?

I ask because I'am switching often between both Networks, and this will be much easier.

73 de Mario, DC7JZB

**Comment by dg9vh** [comment]
@dc7jzb actually it is not implemented in the repository, only a test by sa7bnt. I would do it into the repository by myself I think next week. This weekend I am preparing our repeater and so on for showing at the "SaarLorLux Amateurfunktag", so I have not much time left for doing some programming.

But this feature is on the to-do-list.

**Comment by dg9vh** [comment]
closed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/bf8e180ee9ef10e57cf9c989c1f9333184e91054
