### ISSUE TITLE
 Fixing Actual Current Mode when disabled extdlookup and adding network name after DMR-Master-address

### ISSUE THREAD

**Issue by pjao** [dg9vh/MMDVMHost-Dashboard#60]
Hi there,

With this pull (https://github.com/dg9vh/MMDVMHost-Dashboard/commit/c1893cd84742f72a272f0d4c0d47a258067291e3) if you don't enable network switching, after the network DMR-Master-address it appears only "()" because is not defined a default network...

Sugestion: 
If no network defined, than only DMR-Master-address 
or
Setup the default network name

Thanks
Paulo - CT2JAY

**Comment by dg9vh** [comment]
Yes, right, would be fixed this evening...

**Comment by dg9vh** [comment]
fixed with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/2e224eea7cd7f9770e84c82a384f1a96f877edbb
