### ISSUE TITLE
Dashboard don't show Callsigns after Network Change

### ISSUE THREAD

**Issue by dc7jzb** [dg9vh/MMDVMHost-Dashboard#61]
After changing the Network via Dashboard, it don't show the Callsign anymore, only the ID.

I had something similar by changing in the same way via Bashscript and only restarting MMDVMHost.
I found no other solution then a reboot of the Raspi in the Bashscripts after copying the ini File.

Or is there something wrong in my .ini ?

![dashboard_call](https://cloud.githubusercontent.com/assets/2844409/19982070/cec7f396-a204-11e6-90a9-bb89af091a7a.PNG)

**Comment by dg9vh** [comment]
how did you create the two ini-files? Normally you should copy the existing MMDVM.ini into the corresponding ini-File (for example DMRPLUS.ini) and then copy this file into BRANDMEISTER.ini and change master/port-combination + password.

It seems, that you did not configure DMRIds.dat correctly in the new ini-files.

**Comment by dc7jzb** [comment]
Checked it now. In both ini's
LookupFile=DMRIds.dat
so this looks right.

But I have rebooted the Raspi now without touching or changing the ini and
now I see the Callsigns.

Could it be a restart issue with MMDVMHost ?

Am Donnerstag, 3. November 2016 schrieb Kim - DG9VH :

**Comment by dg9vh** [comment]
@dc7jzb please configure absolute paths for the lookup-file.
For example:
LookupFile=/home/pi/MMDVMHost/DMRIds.dat

**Comment by dc7jzb** [comment]
Thats it. Absolute path works.

I worked with the default of the standard ini in BMLight.
There it is without the path.

Thanks ;)

Am Donnerstag, 3. November 2016 schrieb Kim - DG9VH :

**Comment by dg9vh** [comment]
Ok, tnx for info :-)
Now closing this issue :-) Have much fun!
