### ISSUE TITLE
What is wrong with the time in currently txing?

### ISSUE THREAD

**Issue by hardwarewizz** [dg9vh/MMDVMHost-Dashboard#63]
This is since the last updates via GIT. Is it a human provided bug or something else?

73 Walter PD2WGN

![bugorownfault](https://cloud.githubusercontent.com/assets/8209445/20028835/7de31cd8-a33c-11e6-92a9-f08fcf774e2c.jpg)

**Comment by dg9vh** [comment]
What version you are using? See footer

**Comment by hardwarewizz** [comment]
This is my current version:

![bugorownfault1](https://cloud.githubusercontent.com/assets/8209445/20028960/db4b28ae-a33f-11e6-8363-2ac178608316.jpg)

**Comment by dg9vh** [comment]
hm... can't see the problem. If I change on my test-system to your timezone, it works perfectly... even changeing to other timezones works perfect. Sure you cleaned up your browser's cache and disabled any proxy in the middle?

**Comment by hardwarewizz** [comment]
Thnx Kim for the support,

I did some research and when I set the timezone in setup.php to UTC the TX-Time starts normal from 0s and further. The time in UTC notation is for me -3600 seconds. I purged the browser cache and renewed the dashboard code on my pi with git clone. Not a big problem for me but it looks strange... HI ;-)

73 Walter PD2WGN

**Comment by dg9vh** [comment]
@hardwarewizz I'll keep an eye on it... as I said: on my test-system it is ok.
What's your locale-settings? Would you try to test following:

LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by hardwarewizz** [comment]
Hi Kim, 

No problem at all but where do i change these setting?

73 Walter PD2WGN

**Comment by dg9vh** [comment]
Sorry, I meant timezone-settings - see raspi-config... internationalisation... timezone... on my test-system it is set to utc...

**Comment by dg9vh** [comment]
also when setting it to berlin, no problem

**Comment by hardwarewizz** [comment]
My setting was Europe/Amsterdam and set it to UTC. No changes to the TX-Time

**Comment by dg9vh** [comment]
strange ...

would examine this if found a system where this happens, too and I can debug on.

**Comment by hardwarewizz** [comment]
OK... I wait and do some local experimentation. I let you know when something positive happens.
Anyway thnx for your support.

**Comment by dg9vh** [comment]
@hardwarewizz could you check if in /usr/share/zoneinfo the symlink from UTC to ZULU is correctly set?
If not, reinstall tzdata and test again. Tnx.

**Comment by dc7jzb** [comment]
Same here, looks like it changes with the difference to UTC.
Locale all DE ,Symlink from UTC to Zulu looks correct.
![timezone_berlin](https://cloud.githubusercontent.com/assets/2844409/20106280/df73b65c-a5d4-11e6-8578-a6df1c85dac8.PNG)
![timezone_brunei](https://cloud.githubusercontent.com/assets/2844409/20106278/df7359e6-a5d4-11e6-979c-027f0565a40c.PNG)
![timezone_utc](https://cloud.githubusercontent.com/assets/2844409/20106279/df735c70-a5d4-11e6-9d16-d8db9d735603.PNG)

**Comment by hardwarewizz** [comment]
Today a whole new installation of my MMDVMHost image. Problem is the same as before. The symboliclink from UTC to Zulu looks correct and was the same as in my old image.

**Comment by dg9vh** [comment]
Could you please git pull and test, if this fixes the issue? If not, get info back to me.

**Comment by hardwarewizz** [comment]
Hi Kim,
Works great, the tx-time counts up now from zero and further.
Great work and support.

Many thanks and keep up the good work.

73 Walter PD2WGN
