### ISSUE TITLE
Problem with "stop refreshing" 

### ISSUE THREAD

**Issue by faxe2110** [dg9vh/MMDVMHost-Dashboard#64]
I got this info window, looks like there's an issue.
73 SA7BNT

![bildschirmfoto 2016-11-07 um 23 24 46](https://cloud.githubusercontent.com/assets/7265595/20078993/0cb7110a-a543-11e6-9d26-fa2b7a581831.png)
![bildschirmfoto 2016-11-07 um 23 24 55](https://cloud.githubusercontent.com/assets/7265595/20078992/0caab072-a543-11e6-8ce0-0660cd58e5fd.png)

**Comment by scotta1980** [comment]
i have started getting this problem again have updated to the latest dashboard but still getting this

**Comment by dg9vh** [comment]
@scotta1980 do you get this error when calling the "stop refresh"-link or directly when opening the dashboard?

**Comment by scotta1980** [comment]
i get this when opening the dashboard but its strang if i click stop refresh close browser then reload it work ok again  http://mm3lso.ddns.net/

**Comment by scotta1980** [comment]
also after the problem it wont show Last Heard now

**Comment by scotta1980** [comment]
ok think i have found the problem after deleting the mmdvm log file and restarting mmdvmhost dashboard working again don't get the error

**Comment by dg9vh** [comment]
ok.
