### ISSUE TITLE
what is this ??

### ISSUE THREAD

**Issue by iw9grl** [dg9vh/MMDVMHost-Dashboard#69]
![image](https://cloud.githubusercontent.com/assets/16877668/21741568/77ccfea2-d4da-11e6-96b8-ed8b4d02ebdb.png)

**Comment by phl0** [comment]
Seems like that is an error that happened during parsing of the logs. Does that appear regularly?

**Comment by dg9vh** [comment]
sometimes it happens that webservers deliver an error 500 or something instead of the expected AJAX-Data... can't reproduce the conditions when this happens...

**Comment by s-s-s** [comment]
Hi! Got the same error after updating the MMDVHost up to build 20170501
(
I went back to the old version 20170206
