### ISSUE TITLE
Not changed label color for active or inactive mode

### ISSUE THREAD

**Issue by YV5OF** [dg9vh/MMDVMHost-Dashboard#7]
Hi,
Today MMDVM release new update for Host-Dashboard ( commit 1b8d89b ), and active or inactive modes show no color difference.

73!

**Comment by dg9vh** [comment]
Hi, what color is shown on label, green or grey?

**Comment by ve1aic** [comment]
GREY for my default
-Great

**Comment by dg9vh** [comment]
So, please give the new commit a try. I think, the problem would be solved now. Please feedback!

**Comment by dg9vh** [comment]
Sorry, NOW please checkout again, when checked before 1 minute ago..
I forgot to remove my test-configuration :-)

**Comment by YV5OF** [comment]
I just upgraded and observed the same, and I think the callsing repeater 
![captura de pantalla 2016-05-10 a las 12 03 19 p m](https://cloud.githubusercontent.com/assets/19210807/15153501/75409fc8-16a7-11e6-8f41-e4bf115ff89e.png)
disappeared, which is the title.

**Comment by ve1aic** [comment]
Yes it works great now.

Minor error to check:
  PHP Notice:  Undefined offset: 1 in 
/var/www/html/include/functions.php on line 35

-Ron

**Comment by YV5OF** [comment]
Done my friend....
![captura de pantalla 2016-05-10 a las 12 07 36 p m](https://cloud.githubusercontent.com/assets/19210807/15153609/d3c8c1f6-16a7-11e6-8068-42904dca36ca.png)

**Comment by YV5OF** [comment]
For me closed...

**Comment by dg9vh** [comment]
@ve1aic can't reproduce your error...
