### ISSUE TITLE
High BER % aren't always parsed correctly

### ISSUE THREAD

**Issue by m1geo** [dg9vh/MMDVMHost-Dashboard#73]
It seems that sometimes the BER% is not correctly reported, and the BER are shown as 0.00% and RSSI values are missing.

The most recent examples are shown below 

![g3obx_dash](https://cloud.githubusercontent.com/assets/758615/21777286/19017cdc-d696-11e6-96e7-c92b9a721649.png)

![g3obx_dash2](https://cloud.githubusercontent.com/assets/758615/21777291/1c426e92-d696-11e6-94f9-a84c15b36c06.png)

And differently here:

![g3obx_dash3](https://cloud.githubusercontent.com/assets/758615/21777458/d61d44cc-d696-11e6-9534-2eb0b5891e1a.png)

![g3obx_dash4](https://cloud.githubusercontent.com/assets/758615/21777460/d8ef2daa-d696-11e6-966f-4ed46078d2f6.png)

This callsign isn't unique, it was just the last occurrence.

If you need more logs, etc, please email me, and I'll send logs over...

**Comment by m1geo** [comment]
If someone can point me in the right direction, I can try to debug this. I have been poking around in include/functions.php but not really sure.

**Comment by dg9vh** [comment]
Maybe @phl0 can take a look at the code?

**Comment by phl0** [comment]
Sure. Can you provide me with the corresponding logs?

**Comment by phl0** [comment]
Upz. I saw that you provided the logs already. I will look into this.

**Comment by dg9vh** [comment]
@m1geo could you paste the logfile as text, please so @phl0 can put it into a file for testing?

@phl0 tnx for taking the challenge... actually I am out of time due some family things...

**Comment by m1geo** [comment]
Thanks, both.

@phl0 Do you want them emailed to you, instead of here? And sorry to disturb you, @dg9vh

**Comment by m1geo** [comment]
Logs emailed to @phl0

**Comment by dg9vh** [comment]
@m1geo No problem George...

**Comment by phl0** [comment]
Seems like the dashboard handles log lines that contain "transmission lost" in a different way so that BER and RSSI are simply not displayed. Further investigating ...

**Comment by phl0** [comment]
So its not the high BER values that cause the problem here. Its just an error of the Dashboard parsing the log correctly. Also checked the sources of MMDVMHost. Loss cannot be reported from RF transmissions as that is simply there only for incoming network transmissions. So that is another error here. I commited a fix (ref. cd5412e7f5704e8b82265e7f5037e02280f8362a).

@m1geo Could you please test and report?

**Comment by dg9vh** [comment]
@phl0 tnx for your work :-) As you saw, you are able to do some futher things now :-)

**Comment by phl0** [comment]
@dg9vh And I shamelessly made use of it :-)

**Comment by dg9vh** [comment]
@phl0 so hatte ich das auch vorgesehen :+1:

**Comment by phl0** [comment]
@m1geo Can we close this issue then?
