### ISSUE TITLE
DMR TS1 last linked to ...

### ISSUE THREAD

**Issue by g0wfv** [dg9vh/MMDVMHost-Dashboard#8]
Slot 1 should **_never**_ be "linked" to anything making that entry redundant - unless you change it to the last TG heard on that TS?

**Comment by dg9vh** [comment]
Yes, you are right. It's on the roadmap. Maybe this evening.

**Comment by dg9vh** [comment]
Now corrected with https://github.com/dg9vh/MMDVMHost-Dashboard/commit/26b8b15d2b2ed29b56f17d7de94019a4564f10c6

Mni tnx for your inputs!

**Comment by g0wfv** [comment]
Looking good :)

On Sat, May 14, 2016 at 7:53 PM Kim - DG9VH notifications@github.com
wrote:

> Closed #8 https://github.com/dg9vh/MMDVMHost-Dashboard/issues/8.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/8#event-660788952
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
Mni tnx!
I used the traffic in TG91 this afternoon to implement it. I read in MMDVM-Yahoo-Group about many OM complaining about this traffic of "no use" but for me it was the best situation to get traffic for testing without doing any own action :smile:

**Comment by g0wfv** [comment]
Hahahahaha if git had emoticons, I would be using the one with the laughing
face whilst crying!  Best use of the WW net yet - Sir, you deserve a medal!

On Sat, May 14, 2016 at 8:08 PM Kim - DG9VH notifications@github.com
wrote:

> Mni tnx!
> I used the traffic in TG91 this afternoon to implement it. I read in
> MMDVM-Yahoo-Group about many OM complaining about this traffic of "no use"
> but for me it was the best situation to get traffic for testing without
> doing any own action [image: :smile:]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/8#issuecomment-219237713
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
Well... Yes... "missusage" of such events is my personal
special-feature. Years ago I regularly used contests on shortwave to
optimize antennas and band-filters because I don't own any frequency
analyzers and so on...

Ok for now... You are welcome to feed me with ideas of your own to
improve this dashboard.

73
Kim
