### ISSUE TITLE
RSSI output

### ISSUE THREAD

**Issue by faxe2110** [dg9vh/MMDVMHost-Dashboard#81]
![bildschirmfoto 2017-01-16 um 19 19 46](https://cloud.githubusercontent.com/assets/7265595/21994885/41af576c-dc22-11e6-972d-40fb2733061e.png)
![bildschirmfoto 2017-01-16 um 19 19 55](https://cloud.githubusercontent.com/assets/7265595/21994888/443a81aa-dc22-11e6-8afe-7ad133a6deaf.png)

I´m wonder why the RSSI output is different to the BM Dashboard RSSI??
Why not take the same here like BM (RSSI max)

Greeting 
SA7BNT/SG7BNT
Tim

**Comment by phl0** [comment]
We have all three values on the dashboard. Average is shown directly. You can see the min and max values if you hover the mouse over the average value.

**Comment by faxe2110** [comment]
Yes i know, but still the first view is what you get. Not important but just a reflexion.

**Comment by dg9vh** [comment]
My Idea could be to make the string formatable in setup.php by tags like %min, %max, %avg and supersede these when generating the page to the designed string by the user... so with this, it could be possible for the users to make the line under the icon to show like they want it, for examle: min/max/avg or (min, max, avg) or only min - max or something else they want...

Good idea?

**Comment by phl0** [comment]
Maybe a little simpler: Select the value that should be displayed in setup.php (min, max or avg) and let the tooltip as it is?

**Comment by dg9vh** [comment]
That was my idea but with the ability to define a free text to format it... the tooltip would be untouched

**Comment by phl0** [comment]
@faxe2110 Please test https://github.com/dg9vh/MMDVMHost-Dashboard/commit/163b358db350d584749d6e95de836974b014781c and give feedback.

**Comment by dg9vh** [comment]
@faxe2110 is it working as you wanted? Then I can close this...

**Comment by phl0** [comment]
Closed after positive result by @faxe2110
