### ISSUE TITLE
MMDVMHost Version in page header

### ISSUE THREAD

**Issue by g0wfv** [dg9vh/MMDVMHost-Dashboard#9]
This seems to be pulling either the current date or the date from the log filename for display rather than the actual version of MMDVMHost.  (As below ...)

MMDVM-Dashboard by DG9VH for Repeater: G0WFV
MMDVMHost **v2016-05-14** by G4KLX

**Comment by dg9vh** [comment]
I use following function for detecting changetime of MMDVMHost-file:

filectime
(PHP 4, PHP 5, PHP 7)
filectime — Gets inode change time of file

So the question is, did you change location of file or something today? On my reference-installation it is correct:
MMDVM-Dashboard by DG9VH for Repeater: DG9VH
MMDVMHost v2016-05-13 by G4KLX

because I git pull and make an actual version yesterday.

Please check on your side what creation-date your file has.

**Comment by g0wfv** [comment]
Yes, the filectime will be the time (or date in this case) of when I
compiled the executable (ie today - as I am compiling a few times a day at
the moment!)  this will be the same for anyone who "rolls their own"
executable.

I think what you need to look for is the last occurrence of the line as
follows in the log file, however it may not exist if the system has been up
and running for a few days!

_M: 2016-05-14 14:20:45.043 MMDVMHost-20160505 is starting_

or if the source code exists on the system the version is in Version.h

_const char_ VERSION = "20160505";*

There is currently no -v|--version command line argument in MMDVMHost -
perhaps I could write something into the code <grin>

On Sat, May 14, 2016 at 7:43 PM Kim - DG9VH notifications@github.com
wrote:

> I use following function for detecting changetime of MMDVMHost-file:
> 
> filectime
> (PHP 4, PHP 5, PHP 7)
> filectime — Gets inode change time of file
> 
> So the question is, did you change location of file or something today? On
> my reference-installation it is correct:
> MMDVM-Dashboard by DG9VH for Repeater: DG9VH
> MMDVMHost v2016-05-13 by G4KLX
> 
> because I git pull and make an actual version yesterday.
> 
> Please check on your side what creation-date your file has.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219236450
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
Well... the 2016-05-05 is the version of the MMDVM-firmware I think, because in my log it's also: MMDVMHost-20160505 is starting but my files in the sources are fresh files from yesterday with actual changes...

But my firmware in my MMDVM-Arduino is dated 2016-05-05 because Bruce flashed this when selling it to me :grinning: 

It would be a very hard thing to refer to the right version-number I think. The question is: what would one see: the firmware-version or the software-version... or both? I think it could also be a point to put those info from log into the Repeater-Info-Section... but the other problem is: the dashboard only grabs the actual logfile from the actual date. If your system runs 24/7 it would happen to not to find those line in the actual line, because the host is running for 5 days without restarting... so no info in log...

If you got any idea or if you got very good connections to Jonathan to get him to implement a --version-function by asking him for a beer, hi, I think it would be much less missunderstanding :+1:

**Comment by g0wfv** [comment]
Yes that's what I was getting at - the versions may never appear in every
log if the system is up 24/7.

On Sat, May 14, 2016 at 8:04 PM Kim - DG9VH notifications@github.com
wrote:

> Well... the 2016-05-05 is the version of the MMDVM-firmware I think,
> because in my log it's also: MMDVMHost-20160505 is starting but my files in
> the sources are fresh files from yesterday with actual changes...
> 
> But my firmware in my MMDVM-Arduino is dated 2016-05-05 because Bruce
> flashed this when selling it to me [image: :grinning:]
> 
> It would be a very hard thing to refer to the right version-number I
> think. The question is: what would one see: the firmware-version or the
> software-version... or both? I think it could also be a point to put those
> info from log into the Repeater-Info-Section... but the other problem is:
> the dashboard only grabs the actual logfile from the actual date. If your
> system runs 24/7 it would happen to not to find those line in the actual
> line, because the host is running for 5 days without restarting... so no
> info in log...
> 
> If you got any idea or if you got very good connections to Jonathan to get
> him to implement a --version-function by asking him for a beer, hi, I think
> it would be much less missunderstanding [image: :+1:]
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219237494
> 
> ## 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
Leave me with it, I'll have a think ....

On Sat, May 14, 2016 at 8:09 PM Tony Corbett tonyc.uk@gmail.com wrote:

> Yes that's what I was getting at - the versions may never appear in every
> log if the system is up 24/7.
> 
> On Sat, May 14, 2016 at 8:04 PM Kim - DG9VH notifications@github.com
> wrote:
> 
> > Well... the 2016-05-05 is the version of the MMDVM-firmware I think,
> > because in my log it's also: MMDVMHost-20160505 is starting but my files in
> > the sources are fresh files from yesterday with actual changes...
> > 
> > But my firmware in my MMDVM-Arduino is dated 2016-05-05 because Bruce
> > flashed this when selling it to me [image: :grinning:]
> > 
> > It would be a very hard thing to refer to the right version-number I
> > think. The question is: what would one see: the firmware-version or the
> > software-version... or both? I think it could also be a point to put those
> > info from log into the Repeater-Info-Section... but the other problem is:
> > the dashboard only grabs the actual logfile from the actual date. If your
> > system runs 24/7 it would happen to not to find those line in the actual
> > line, because the host is running for 5 days without restarting... so no
> > info in log...
> > 
> > If you got any idea or if you got very good connections to Jonathan to
> > get him to implement a --version-function by asking him for a beer, hi, I
> > think it would be much less missunderstanding [image: :+1:]
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219237494
> > 
> > ## 
> 
> A J Corbett
> 
> G0WFV
> 
> ## 

A J Corbett

G0WFV

**Comment by ve1aic** [comment]
The 'version' number should refer to MMDVMHost software only.

Also, Jonathan has his own idea on when to change the version number.
Its still 2010505 but the latest commit is 20160514.

So if I update my files and recompile I want it to reflect the fact that 
its newer than the official 'version' number...as listed in Version.h code.

I think the best way would be use the file date of the actual code but 
that may not be possible.

Using the date of the 'executable' as Kim does it now is probably the 
best compromise until Jonathan includes a 'sub-'version number for 
updates between versions.

-Ron
VE1AIC

**Comment by g0wfv** [comment]
The commits from today were my doing - I updated the DMRIDs file and a
small addition to the DMR code to try to fix an issue.

I've managed to put a few things in to the code most days this week
sometimes 2 or 3 commits a day - most of them will never affect the
majority as they were to do with the HD44780 LCD displays, but the 2 today
will affect the masses!

Anyway, back to the subject at hand, It's a tricky one as people can be
running all different variations of version/sub-versions depending on which
commit they pull from git.  Personally I can live without any version
numbering on the dash for now.  Once Jon has decided to go for a release
and the code is fairly static it could be more appropriate to display the
version then?  Who knows, maybe I will have crept a version routine into
the code for you by then ;-)

On Sat, May 14, 2016 at 8:15 PM Ron VE1AIC notifications@github.com wrote:

> The 'version' number should refer to MMDVMHost software only.
> 
> Also, Jonathan has his own idea on when to change the version number.
> Its still 2010505 but the latest commit is 20160514.
> 
> So if I update my files and recompile I want it to reflect the fact that
> its newer than the official 'version' number...as listed in Version.h code.
> 
> I think the best way would be use the file date of the actual code but
> that may not be possible.
> 
> Using the date of the 'executable' as Kim does it now is probably the
> best compromise until Jonathan includes a 'sub-'version number for
> updates between versions.
> 
> -Ron
> VE1AIC
> 
> On 2016-05-14 16:04, Kim - DG9VH wrote:
> 
> > Well... the 2016-05-05 is the version of the MMDVM-firmware I think,
> > because in my log it's also: MMDVMHost-20160505 is starting but my files
> > in the sources are fresh files from yesterday with actual changes...
> > 
> > But my firmware in my MMDVM-Arduino is dated 2016-05-05 because Bruce
> > flashed this when selling it to me :grinning:
> > 
> > It would be a very hard thing to refer to the right version-number I
> > think. The question is: what would one see: the firmware-version or the
> > software-version... or both? I think it could also be a point to put
> > those info from log into the Repeater-Info-Section... but the other
> > problem is: the dashboard only grabs the actual logfile from the actual
> > date. If your system runs 24/7 it would happen to not to find those line
> > in the actual line, because the host is running for 5 days without
> > restarting... so no info in log...
> > 
> > If you got any idea or if you got very good connections to Jonathan to
> > get him to implement a --version-function by asking him for a beer, hi,
> > I think it would be much less missunderstanding :+1:
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219237494
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219238052
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
Or I delegate one to deliver Jon a beer at HAMRADIO this year :laughing: 

Well, I think it would be easy to edit the index.php to comment the line out if one don't want to show this info. Or it could be made configureable in config.php if "masses" of persons not able to edit php-code in such cases are out there.

Also thinking about this alternative... Leaving open to catch more ideas from different persons maybe. It's not a hot topic or functional issue so no problem to leave it open for a while and think conceptional about it.

**Comment by g0wfv** [comment]
Good plan, Batman!

OK, how's this for a quick hack ...

tonyc@g0wfv:~/MMDVMHost$ ./MMDVMHost
Couldn't open the .ini file - /etc/MMDVM.ini
MMDVMHost-20160505: cannot read the .ini file

Just call MMDVMHost with no arguments and it throws up an error

I can push this to Jon's code and see if he takes it?

You could then use something like ...

MMDVMHost by G4KLX - Version: 20160505 (compiled 14 May 16)

... in the header? (taking the file date to be the compiled date?)

On Sat, May 14, 2016 at 8:38 PM Kim - DG9VH notifications@github.com
wrote:

> Or I delegate one to deliver Jon a beer at HAMRADIO this year [image:
> :laughing:]
> 
> Well, I think it would be easy to edit the index.php to comment the line
> out if one don't want to show this info. Or it could be made configureable
> in config.php if "masses" of persons not able to edit php-code in such
> cases are out there.
> 
> Also thinking about this alternative... Leaving open to catch more ideas
> from different persons maybe. It's not a hot topic or functional issue so
> no problem to leave it open for a while and think conceptional about it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219239217
> 
> ## 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
If you want to play and test, I will be committing the code change to my
develop branch (https://github.com/g0wfv/MMDVMHost/tree/develop)

On Sat, May 14, 2016 at 9:19 PM Tony Corbett tonyc.uk@gmail.com wrote:

> Good plan, Batman!
> 
> OK, how's this for a quick hack ...
> 
> tonyc@g0wfv:~/MMDVMHost$ ./MMDVMHost
> Couldn't open the .ini file - /etc/MMDVM.ini
> MMDVMHost-20160505: cannot read the .ini file
> 
> Just call MMDVMHost with no arguments and it throws up an error
> 
> I can push this to Jon's code and see if he takes it?
> 
> You could then use something like ...
> 
> MMDVMHost by G4KLX - Version: 20160505 (compiled 14 May 16)
> 
> ... in the header? (taking the file date to be the compiled date?)
> 
> On Sat, May 14, 2016 at 8:38 PM Kim - DG9VH notifications@github.com
> wrote:
> 
> > Or I delegate one to deliver Jon a beer at HAMRADIO this year [image:
> > :laughing:]
> > 
> > Well, I think it would be easy to edit the index.php to comment the line
> > out if one don't want to show this info. Or it could be made configureable
> > in config.php if "masses" of persons not able to edit php-code in such
> > cases are out there.
> > 
> > Also thinking about this alternative... Leaving open to catch more ideas
> > from different persons maybe. It's not a hot topic or functional issue so
> > no problem to leave it open for a while and think conceptional about it.
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219239217
> > 
> > ## 
> 
> A J Corbett
> 
> G0WFV
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
If he can live with this, I would be able to manage the visualization.

I need a bit of your assistance, Robin, hi.

I'll see, we are going to be such a good combination like Hamilton and
Mercedes :-)

I'll take a look at your version of MMDVM.

73 de Kim
DG9VH

**Comment by g0wfv** [comment]
Jon didn't go for that implementation - but he will go for a -v | --version
option (which I'll have a look at tomorrow at some point!)

On Sat, May 14, 2016 at 9:28 PM Kim - DG9VH notifications@github.com
wrote:

> If he can live with this, I would be able to manage the visualization.
> 
> I need a bit of your assistance, Robin, hi.
> 
> I'll see, we are going to be such a good combination like Hamilton and
> Mercedes :-)
> 
> I'll take a look at your version of MMDVM.
> 
> 73 de Kim
> 
> DG9VH
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219249884
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
I tested with your version in https://github.com/dg9vh/MMDVMHost-Dashboard/tree/develop
this was working...

**Comment by dg9vh** [comment]
hm... ok, we'll wait for tomorrow... but you'll see - I am willing to manage

**Comment by g0wfv** [comment]
I'm about to commit a new version to my develop branch

./MMDVMHost -v or ./MMDVMHost --version will give

MMDVMHost 20160514

On Sat, May 14, 2016 at 10:50 PM Kim - DG9VH notifications@github.com
wrote:

> hm... ok, we'll wait for tomorrow... but you'll see - I am willing to
> manage
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219253485
> 
> ## 

A J Corbett

G0WFV

**Comment by g0wfv** [comment]
PR from my develop branch created to include the new -v flag in MMDVMHost.

On Sat, May 14, 2016 at 11:24 PM Tony Corbett tonyc.uk@gmail.com wrote:

> I'm about to commit a new version to my develop branch
> 
> ./MMDVMHost -v or ./MMDVMHost --version will give
> 
> MMDVMHost 20160514
> 
> On Sat, May 14, 2016 at 10:50 PM Kim - DG9VH notifications@github.com
> wrote:
> 
> > hm... ok, we'll wait for tomorrow... but you'll see - I am willing to
> > manage
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/dg9vh/MMDVMHost-Dashboard/issues/9#issuecomment-219253485
> > 
> > ## 
> 
> A J Corbett
> 
> G0WFV
> 
> ## 

A J Corbett

G0WFV

**Comment by dg9vh** [comment]
Will test your parch this evening. Merged in develop

**Comment by dg9vh** [comment]
closed with patch https://github.com/dg9vh/MMDVMHost-Dashboard/commit/d0af39d6699703aae5f8304d9509d9f3b0d8665c
