### ISSUE TITLE
Embedded Talker Alias

### ISSUE THREAD

**Issue by pjao** [dg9vh/MMDVMHost-Dashboard#94]
Hello,

With the new BrandMeister 20170208-124154 - Added call enrichment with Talker Alias (to groups calls only), do any one as plans to take care of those messages into the dashboard? Is it useful?
 
Paulo - CT2JAY

**Comment by dg9vh** [comment]
@pjao If those info is available in the log of MMDVMHost, it would be possible to be integrated soon. Till now I can't find some info in the log.

If you have loglines showing that info, please post them here.
Tnx

Kim

**Comment by pjao** [comment]
@dg9vh here it goes.

It depends on your master version.

[MMDVM-2017-02-08.zip](https://github.com/dg9vh/MMDVMHost-Dashboard/files/761547/MMDVM-2017-02-08.zip)

**Comment by dg9vh** [comment]
@pjao what Loglevel you are using in your MMDVM.ini? The Dashboard is only running with good performance at LogLevel=2... Your log provides many many lines more that gives me no clue what talker alias it should contain... example:

M: 2017-02-08 15:22:47.446 DMR Slot 2, received network voice header from CT1CRR to TG 268
D: 2017-02-08 15:22:48.199 DMR Slot 2, Embedded Talker Alias Header
D: 2017-02-08 15:22:48.200 0000:  04 00 6C 43 54 31 43 52 A4                         *..lCT1CR.*
D: 2017-02-08 15:22:48.932 DMR Slot 2, Embedded Talker Alias Block 1
D: 2017-02-08 15:22:48.932 0000:  05 00 20 44 4D 52 20 49 88                         *.. DMR I.*
D: 2017-02-08 15:22:49.653 DMR Slot 2, Embedded Talker Alias Block 2
D: 2017-02-08 15:22:49.653 0000:  06 00 3A 20 32 36 38 33 62                         *..: 2683b*
D: 2017-02-08 15:22:50.428 DMR Slot 2, Embedded Talker Alias Block 3
D: 2017-02-08 15:22:50.428 0000:  07 00 33 33 00 00 00 00 00                         *..33.....*

That shows me, that CT1CRR is transmitting but I can't see, what alias exactly is shown on the Hytera... could you give me some light into the dark?

**Comment by pjao** [comment]
@dg9vh with LogLevel=2 there is no information with "Talker Alias", only with LogLevel=1, that could be the light...

Maybe have to be translated first by the mmdvmhost, and then used by the dashboard.

**Comment by dg9vh** [comment]
@pjao due to the performance issues and the fact that the dashboard would stop running with logs bigger than 30 MB or so LogLevel 1 is not recommended to use... Maybe, if Jonathan would go with it, it could be possible to print only the first occurence of the alias-block in LogLevel 2... I think we should give the whole thing a week or two to be stabilized by the BM-teams and then ask Johnathan to modify LogLevel 2 in that way... just as an idea.

**Comment by pjao** [comment]
@dg9vh Good idea! I'll open an issue on MMDVMHost...

Let's see if could be possible! (https://github.com/g4klx/MMDVMHost/issues/254)

**Comment by pjao** [comment]
Hi @dg9vh !

New version of MMDVMHost has now "Talker Alias" available on LogLevel=2 without repetition.

Can you work on it? 

Header starts with "04 00" (Callsign)
Block 1 with "05 00" (name)
Block 2 with "06 00" (if exists join with block 1)
Block 3 with "07 00" (if exists join with block 2 & 1)

For the last character you need to divide with two. 

Example:
M: 2017-02-13 11:23:41.990 DMR Slot 2, Embedded Talker Alias Header
M: 2017-02-13 11:23:41.990 0000:  04 00 56 43 54 35 4B 4E 90                         *..VCT5KN.*

Should be CT5KNH as 90(hex)/2=48 (hex) ='H' (ASCII)

M: 2017-02-13 11:24:27.528 0000:  04 00 58 43 54 32 4A 53 A6                         *..XCT2JS.*
Should be CT2JSS as A6(hex)/2=53 (hex) = 'S' (ASCII)

If it is "00" do nothing.

**Comment by dg9vh** [comment]
I'll take a look at it this evening.

**Comment by dg9vh** [comment]
@pjao I am not sure, if your information about converting the last character of the line would be fully correct... but I try doing my best :-)

**Comment by pjao** [comment]
@dg9vh I've tried with several examples:

CT1ELH:
M: 2017-02-13 16:44:23.728 0000:  04 00 5A 43 54 31 45 4C 90                         *..ZCT1EL.*
90(hex) / 2 (hex) = 48 (hex) = 72 (DEC) = H (ASCII)

CT1AFS:
M: 2017-02-13 16:42:23.879 0000:  04 00 5A 43 54 31 41 46 A6                         *..ZCT1AF.*
A6(hex) / 2 (hex) = 53 (hex) = 83 (DEC) = S (ASCII)

CT2KEV:
M: 2017-02-13 16:41:52.020 0000:  04 00 56 43 54 32 4B 45 AC                         *..VCT2KE.*
AC(hex) / 2 (hex) = 56 (hex) = 86 (DEC) = V (ASCII)

HEX Calculator (http://www.calculator.net/hex-calculator.html?)
HEX to ASCII converter (http://www.rapidtables.com/convert/number/hex-to-ascii.htm)

**Comment by dg9vh** [comment]
please try https://github.com/dg9vh/MMDVMHost-Dashboard/commit/c5b8592ffb50089ff6d9c8a523961cbd821c2176

take a look at setup.php to switch it on.

**Comment by pjao** [comment]
@dg9vh first look, and it looks fantastic!

Let me see during the day, but it seams very nice.

Thanks Kim!

**Comment by pjao** [comment]
Hi all!

After more than a day, with some more minor corrections you made, it look great and working nice.

It's a good enhancement and for me, it could be closed with success!

**Comment by dg9vh** [comment]
@pjao where you testing with hotspot or repeater (ts1 & ts2)?

If it is working correctly with 2 TSs, I would close it :-)

**Comment by pjao** [comment]
@dg9vh hotspot, so waiting for some one with a repeater to help us!

**Comment by phl0** [comment]
I guess @ernix66 can help out. He is operating a full duplex DMR repeater with two time slots. Have a look at http://dashboard.db0he.de

**Comment by pjao** [comment]
Hi @dg9vh,

Today @g4klx introduced "Demote all of the embedded data dumping to debug level. " - https://github.com/g4klx/MMDVMHost/commit/26010e5b54acc6b9cf8585694f40dde82f0f4954
So, TA is no longer available on log level 2.

Tried to change log level to 1 (debug) and TA appears on the log, and not on the dashboard, I can't understand way...

**Comment by pjao** [comment]
@dg9vh ! 

Good news!

New PR! Tested with success!

Do not forget to add "DumpTAData=1" to you existing MMDVM.ini after EmbeddedLCOnly

https://github.com/g4klx/MMDVMHost/commit/1dbaec9331aedbb66ac96a98cc9af2e3cc403206

**Comment by dg9vh** [comment]
Seems to be working as expected now...
